//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.ScheduledTask.CSMMailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    public partial class JobTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMMailService.JobTaskResult[] JobTaskResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMMailService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMMailService.JobTaskResult[] JobTaskResults {
            get {
                return this.JobTaskResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTaskResultsField, value) != true)) {
                    this.JobTaskResultsField = value;
                    this.RaisePropertyChanged("JobTaskResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMMailService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Common")]
    [System.SerializableAttribute()]
    public partial class StatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BranchCodeNotFoundListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BranchCodeNotFoundList {
            get {
                return this.BranchCodeNotFoundListField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeNotFoundListField, value) != true)) {
                    this.BranchCodeNotFoundListField = value;
                    this.RaisePropertyChanged("BranchCodeNotFoundList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobTaskResult", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    public partial class JobTaskResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumFailedDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfKKWebSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMMailService.StatusResponse StatusResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalEmailReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumFailedDelete {
            get {
                return this.NumFailedDeleteField;
            }
            set {
                if ((this.NumFailedDeleteField.Equals(value) != true)) {
                    this.NumFailedDeleteField = value;
                    this.RaisePropertyChanged("NumFailedDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfEmail {
            get {
                return this.NumOfEmailField;
            }
            set {
                if ((this.NumOfEmailField.Equals(value) != true)) {
                    this.NumOfEmailField = value;
                    this.RaisePropertyChanged("NumOfEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfFax {
            get {
                return this.NumOfFaxField;
            }
            set {
                if ((this.NumOfFaxField.Equals(value) != true)) {
                    this.NumOfFaxField = value;
                    this.RaisePropertyChanged("NumOfFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfKKWebSite {
            get {
                return this.NumOfKKWebSiteField;
            }
            set {
                if ((this.NumOfKKWebSiteField.Equals(value) != true)) {
                    this.NumOfKKWebSiteField = value;
                    this.RaisePropertyChanged("NumOfKKWebSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSR {
            get {
                return this.NumOfSRField;
            }
            set {
                if ((this.NumOfSRField.Equals(value) != true)) {
                    this.NumOfSRField = value;
                    this.RaisePropertyChanged("NumOfSR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMMailService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalEmailRead {
            get {
                return this.TotalEmailReadField;
            }
            set {
                if ((this.TotalEmailReadField.Equals(value) != true)) {
                    this.TotalEmailReadField = value;
                    this.RaisePropertyChanged("TotalEmailRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kiatnakinbank.com/services/CSM/CSMMailService", ConfigurationName="CSMMailService.ICSMMailService")]
    public interface ICSMMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "ox", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "oxResponse")]
        CSM.ScheduledTask.CSMMailService.JobTaskResponse GetMailbox(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "ox", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "oxResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMMailService.JobTaskResponse> GetMailboxAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSMMailServiceChannel : CSM.ScheduledTask.CSMMailService.ICSMMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSMMailServiceClient : System.ServiceModel.ClientBase<CSM.ScheduledTask.CSMMailService.ICSMMailService>, CSM.ScheduledTask.CSMMailService.ICSMMailService {
        
        public CSMMailServiceClient() {
        }
        
        public CSMMailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSMMailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMMailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMMailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSM.ScheduledTask.CSMMailService.JobTaskResponse GetMailbox(string username, string password) {
            return base.Channel.GetMailbox(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMMailService.JobTaskResponse> GetMailboxAsync(string username, string password) {
            return base.Channel.GetMailboxAsync(username, password);
        }
    }
}
