//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Web.DoNotCallBatchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="DoNotCallBatchService.IDoNotCallBatchProcess")]
    public interface IDoNotCallBatchProcess {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDoNotCallBatchProcess/ExportFile", ReplyAction="urn:IDoNotCallBatchProcess/ExportFileResponse")]
        CSM.Service.Messages.DoNotCall.ExportFileResponse ExportFile(CSM.Service.Messages.DoNotCall.ExportFileRequest requet);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDoNotCallBatchProcess/ExportFile", ReplyAction="urn:IDoNotCallBatchProcess/ExportFileResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.DoNotCall.ExportFileResponse> ExportFileAsync(CSM.Service.Messages.DoNotCall.ExportFileRequest requet);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDoNotCallBatchProcess/ExportFileToTOT", ReplyAction="urn:IDoNotCallBatchProcess/ExportFileToTOTResponse")]
        CSM.Service.Messages.DoNotCall.ExportFileResponse ExportFileToTOT(CSM.Service.Messages.DoNotCall.ExportFileToTotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDoNotCallBatchProcess/ExportFileToTOT", ReplyAction="urn:IDoNotCallBatchProcess/ExportFileToTOTResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.DoNotCall.ExportFileResponse> ExportFileToTOTAsync(CSM.Service.Messages.DoNotCall.ExportFileToTotRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoNotCallBatchProcessChannel : CSM.Web.DoNotCallBatchService.IDoNotCallBatchProcess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoNotCallBatchProcessClient : System.ServiceModel.ClientBase<CSM.Web.DoNotCallBatchService.IDoNotCallBatchProcess>, CSM.Web.DoNotCallBatchService.IDoNotCallBatchProcess {
        
        public DoNotCallBatchProcessClient() {
        }
        
        public DoNotCallBatchProcessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoNotCallBatchProcessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoNotCallBatchProcessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoNotCallBatchProcessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSM.Service.Messages.DoNotCall.ExportFileResponse ExportFile(CSM.Service.Messages.DoNotCall.ExportFileRequest requet) {
            return base.Channel.ExportFile(requet);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.DoNotCall.ExportFileResponse> ExportFileAsync(CSM.Service.Messages.DoNotCall.ExportFileRequest requet) {
            return base.Channel.ExportFileAsync(requet);
        }
        
        public CSM.Service.Messages.DoNotCall.ExportFileResponse ExportFileToTOT(CSM.Service.Messages.DoNotCall.ExportFileToTotRequest request) {
            return base.Channel.ExportFileToTOT(request);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.DoNotCall.ExportFileResponse> ExportFileToTOTAsync(CSM.Service.Messages.DoNotCall.ExportFileToTotRequest request) {
            return base.Channel.ExportFileToTOTAsync(request);
        }
    }
}
