//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Web.SendNotificationSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/KK.Service")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REFERENCE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERVICE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYSTEM_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANSACTION_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERNAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD {
            get {
                return this.PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSWORDField, value) != true)) {
                    this.PASSWORDField = value;
                    this.RaisePropertyChanged("PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCE_NO {
            get {
                return this.REFERENCE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.REFERENCE_NOField, value) != true)) {
                    this.REFERENCE_NOField = value;
                    this.RaisePropertyChanged("REFERENCE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERVICE_NAME {
            get {
                return this.SERVICE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SERVICE_NAMEField, value) != true)) {
                    this.SERVICE_NAMEField = value;
                    this.RaisePropertyChanged("SERVICE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYSTEM_CODE {
            get {
                return this.SYSTEM_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.SYSTEM_CODEField, value) != true)) {
                    this.SYSTEM_CODEField = value;
                    this.RaisePropertyChanged("SYSTEM_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANSACTION_DATE {
            get {
                return this.TRANSACTION_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANSACTION_DATEField, value) != true)) {
                    this.TRANSACTION_DATEField = value;
                    this.RaisePropertyChanged("TRANSACTION_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MESSAGE_DETAIL", Namespace="http://schemas.datacontract.org/2004/07/WS_ININ_SendNotification")]
    [System.SerializableAttribute()]
    public partial class MESSAGE_DETAIL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHEQUE_NO_FROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHEQUE_NO_TOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANY_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FROM_ACCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMBER_OF_CHEQUEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRODUCT_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_NO1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESERVE_FIELD1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESERVE_FIELD2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESERVE_FIELD3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESERVE_FIELD4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESERVE_FIELD5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TO_ACCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TO_ACCOUNT_BANK_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANSACTION_DATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMOUNT {
            get {
                return this.AMOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.AMOUNTField, value) != true)) {
                    this.AMOUNTField = value;
                    this.RaisePropertyChanged("AMOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHEQUE_NO_FROM {
            get {
                return this.CHEQUE_NO_FROMField;
            }
            set {
                if ((object.ReferenceEquals(this.CHEQUE_NO_FROMField, value) != true)) {
                    this.CHEQUE_NO_FROMField = value;
                    this.RaisePropertyChanged("CHEQUE_NO_FROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHEQUE_NO_TO {
            get {
                return this.CHEQUE_NO_TOField;
            }
            set {
                if ((object.ReferenceEquals(this.CHEQUE_NO_TOField, value) != true)) {
                    this.CHEQUE_NO_TOField = value;
                    this.RaisePropertyChanged("CHEQUE_NO_TO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANY_NAME {
            get {
                return this.COMPANY_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANY_NAMEField, value) != true)) {
                    this.COMPANY_NAMEField = value;
                    this.RaisePropertyChanged("COMPANY_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FROM_ACCOUNT {
            get {
                return this.FROM_ACCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.FROM_ACCOUNTField, value) != true)) {
                    this.FROM_ACCOUNTField = value;
                    this.RaisePropertyChanged("FROM_ACCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMBER_OF_CHEQUE {
            get {
                return this.NUMBER_OF_CHEQUEField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMBER_OF_CHEQUEField, value) != true)) {
                    this.NUMBER_OF_CHEQUEField = value;
                    this.RaisePropertyChanged("NUMBER_OF_CHEQUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCT_CODE {
            get {
                return this.PRODUCT_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_CODEField, value) != true)) {
                    this.PRODUCT_CODEField = value;
                    this.RaisePropertyChanged("PRODUCT_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCT_DESC {
            get {
                return this.PRODUCT_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUCT_DESCField, value) != true)) {
                    this.PRODUCT_DESCField = value;
                    this.RaisePropertyChanged("PRODUCT_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REF_NO1 {
            get {
                return this.REF_NO1Field;
            }
            set {
                if ((object.ReferenceEquals(this.REF_NO1Field, value) != true)) {
                    this.REF_NO1Field = value;
                    this.RaisePropertyChanged("REF_NO1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REF_NO2 {
            get {
                return this.REF_NO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.REF_NO2Field, value) != true)) {
                    this.REF_NO2Field = value;
                    this.RaisePropertyChanged("REF_NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESERVE_FIELD1 {
            get {
                return this.RESERVE_FIELD1Field;
            }
            set {
                if ((object.ReferenceEquals(this.RESERVE_FIELD1Field, value) != true)) {
                    this.RESERVE_FIELD1Field = value;
                    this.RaisePropertyChanged("RESERVE_FIELD1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESERVE_FIELD2 {
            get {
                return this.RESERVE_FIELD2Field;
            }
            set {
                if ((object.ReferenceEquals(this.RESERVE_FIELD2Field, value) != true)) {
                    this.RESERVE_FIELD2Field = value;
                    this.RaisePropertyChanged("RESERVE_FIELD2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESERVE_FIELD3 {
            get {
                return this.RESERVE_FIELD3Field;
            }
            set {
                if ((object.ReferenceEquals(this.RESERVE_FIELD3Field, value) != true)) {
                    this.RESERVE_FIELD3Field = value;
                    this.RaisePropertyChanged("RESERVE_FIELD3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESERVE_FIELD4 {
            get {
                return this.RESERVE_FIELD4Field;
            }
            set {
                if ((object.ReferenceEquals(this.RESERVE_FIELD4Field, value) != true)) {
                    this.RESERVE_FIELD4Field = value;
                    this.RaisePropertyChanged("RESERVE_FIELD4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESERVE_FIELD5 {
            get {
                return this.RESERVE_FIELD5Field;
            }
            set {
                if ((object.ReferenceEquals(this.RESERVE_FIELD5Field, value) != true)) {
                    this.RESERVE_FIELD5Field = value;
                    this.RaisePropertyChanged("RESERVE_FIELD5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TO_ACCOUNT {
            get {
                return this.TO_ACCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.TO_ACCOUNTField, value) != true)) {
                    this.TO_ACCOUNTField = value;
                    this.RaisePropertyChanged("TO_ACCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TO_ACCOUNT_BANK_NAME {
            get {
                return this.TO_ACCOUNT_BANK_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.TO_ACCOUNT_BANK_NAMEField, value) != true)) {
                    this.TO_ACCOUNT_BANK_NAMEField = value;
                    this.RaisePropertyChanged("TO_ACCOUNT_BANK_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANSACTION_DATE {
            get {
                return this.TRANSACTION_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANSACTION_DATEField, value) != true)) {
                    this.TRANSACTION_DATEField = value;
                    this.RaisePropertyChanged("TRANSACTION_DATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendNotificationSvc.ISendNotification")]
    public interface ISendNotification {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendNotification/VerifyOTPByKKT", ReplyAction="http://tempuri.org/ISendNotification/VerifyOTPByKKTResponse")]
        CSM.Web.SendNotificationSvc.StatusResponse VerifyOTPByKKT(CSM.Web.SendNotificationSvc.RequestParameter request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendNotification/VerifyOTPByKKT", ReplyAction="http://tempuri.org/ISendNotification/VerifyOTPByKKTResponse")]
        System.Threading.Tasks.Task<CSM.Web.SendNotificationSvc.StatusResponse> VerifyOTPByKKTAsync(CSM.Web.SendNotificationSvc.RequestParameter request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Params", WrapperNamespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", IsWrapped=true)]
    public partial class RequestParameter {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult")]
        public CSM.Web.SendNotificationSvc.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=0)]
        public string CALL_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=1)]
        public string CLIENT_IP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=2)]
        public string IDENTIFICATION_TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=3)]
        public string ID_CARD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=4)]
        public CSM.Web.SendNotificationSvc.MESSAGE_DETAIL MESSAGE_DETAIL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=5)]
        public string METHOD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=6)]
        public string TEMPLATE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=7)]
        public string TXN_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/RegisterService/OTPResult", Order=8)]
        public string USER_ACTION;
        
        public RequestParameter() {
        }
        
        public RequestParameter(CSM.Web.SendNotificationSvc.Header header, string CALL_ID, string CLIENT_IP, string IDENTIFICATION_TYPE, string ID_CARD, CSM.Web.SendNotificationSvc.MESSAGE_DETAIL MESSAGE_DETAIL, string METHOD, string TEMPLATE_ID, string TXN_ID, string USER_ACTION) {
            this.header = header;
            this.CALL_ID = CALL_ID;
            this.CLIENT_IP = CLIENT_IP;
            this.IDENTIFICATION_TYPE = IDENTIFICATION_TYPE;
            this.ID_CARD = ID_CARD;
            this.MESSAGE_DETAIL = MESSAGE_DETAIL;
            this.METHOD = METHOD;
            this.TEMPLATE_ID = TEMPLATE_ID;
            this.TXN_ID = TXN_ID;
            this.USER_ACTION = USER_ACTION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DESCRIPTION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ERROR_CODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string STATUS;
        
        public StatusResponse() {
        }
        
        public StatusResponse(string DESCRIPTION, string ERROR_CODE, string STATUS) {
            this.DESCRIPTION = DESCRIPTION;
            this.ERROR_CODE = ERROR_CODE;
            this.STATUS = STATUS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendNotificationChannel : CSM.Web.SendNotificationSvc.ISendNotification, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendNotificationClient : System.ServiceModel.ClientBase<CSM.Web.SendNotificationSvc.ISendNotification>, CSM.Web.SendNotificationSvc.ISendNotification {
        
        public SendNotificationClient() {
        }
        
        public SendNotificationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendNotificationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendNotificationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendNotificationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSM.Web.SendNotificationSvc.StatusResponse CSM.Web.SendNotificationSvc.ISendNotification.VerifyOTPByKKT(CSM.Web.SendNotificationSvc.RequestParameter request) {
            return base.Channel.VerifyOTPByKKT(request);
        }
        
        public string VerifyOTPByKKT(CSM.Web.SendNotificationSvc.Header header, string CALL_ID, string CLIENT_IP, string IDENTIFICATION_TYPE, string ID_CARD, CSM.Web.SendNotificationSvc.MESSAGE_DETAIL MESSAGE_DETAIL, string METHOD, string TEMPLATE_ID, string TXN_ID, string USER_ACTION, out string ERROR_CODE, out string STATUS) {
            CSM.Web.SendNotificationSvc.RequestParameter inValue = new CSM.Web.SendNotificationSvc.RequestParameter();
            inValue.header = header;
            inValue.CALL_ID = CALL_ID;
            inValue.CLIENT_IP = CLIENT_IP;
            inValue.IDENTIFICATION_TYPE = IDENTIFICATION_TYPE;
            inValue.ID_CARD = ID_CARD;
            inValue.MESSAGE_DETAIL = MESSAGE_DETAIL;
            inValue.METHOD = METHOD;
            inValue.TEMPLATE_ID = TEMPLATE_ID;
            inValue.TXN_ID = TXN_ID;
            inValue.USER_ACTION = USER_ACTION;
            CSM.Web.SendNotificationSvc.StatusResponse retVal = ((CSM.Web.SendNotificationSvc.ISendNotification)(this)).VerifyOTPByKKT(inValue);
            ERROR_CODE = retVal.ERROR_CODE;
            STATUS = retVal.STATUS;
            return retVal.DESCRIPTION;
        }
        
        public System.Threading.Tasks.Task<CSM.Web.SendNotificationSvc.StatusResponse> VerifyOTPByKKTAsync(CSM.Web.SendNotificationSvc.RequestParameter request) {
            return base.Channel.VerifyOTPByKKTAsync(request);
        }
    }
}
