//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Web.CSMFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kiatnakinbank.com/services/CSM/CSMFileService", ConfigurationName="CSMFileService.ICSMFileService")]
    public interface ICSMFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FSResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.Common.StatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportNCBTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportBDWTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportCISTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHpTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHRTaskResponse))]
        CSM.Service.Messages.SchedTask.ImportAFSTaskResponse GetFileAFS(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FSResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportAFSTaskResponse> GetFileAFSAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFSResponse")]
        CSM.Service.Messages.SchedTask.ExportAFSTaskResponse ExportFileAFS(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFSResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ExportAFSTaskResponse> ExportFileAFSAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCB", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCBResponse")]
        CSM.Service.Messages.SchedTask.ExportNCBTaskResponse ExportFileNCB(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCB", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCBResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ExportNCBTaskResponse> ExportFileNCBAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DW", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DWResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.Common.StatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportNCBTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportCISTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHpTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHRTaskResponse))]
        CSM.Service.Messages.SchedTask.ImportBDWTaskResponse GetFileBDW(string username, string password, bool skipSftp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DW", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DWResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportBDWTaskResponse> GetFileBDWAsync(string username, string password, bool skipSftp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "IS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "ISResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.Common.StatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportNCBTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportBDWTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHpTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHRTaskResponse))]
        CSM.Service.Messages.SchedTask.ImportCISTaskResponse GetFileCIS(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "IS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "ISResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportCISTaskResponse> GetFileCISAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "P", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "PResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.Common.StatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportNCBTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportBDWTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportCISTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHRTaskResponse))]
        CSM.Service.Messages.SchedTask.ImportHpTaskResponse GetFileHP(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "P", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "PResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportHpTaskResponse> GetFileHPAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "R", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "RResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.Common.StatusResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportAFSTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ExportNCBTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportBDWTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportCISTaskResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CSM.Service.Messages.SchedTask.ImportHpTaskResponse))]
        CSM.Service.Messages.SchedTask.ImportHRTaskResponse GetFileHR(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "R", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "RResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportHRTaskResponse> GetFileHRAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSMFileServiceChannel : CSM.Web.CSMFileService.ICSMFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSMFileServiceClient : System.ServiceModel.ClientBase<CSM.Web.CSMFileService.ICSMFileService>, CSM.Web.CSMFileService.ICSMFileService {
        
        public CSMFileServiceClient() {
        }
        
        public CSMFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSMFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSM.Service.Messages.SchedTask.ImportAFSTaskResponse GetFileAFS(string username, string password) {
            return base.Channel.GetFileAFS(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportAFSTaskResponse> GetFileAFSAsync(string username, string password) {
            return base.Channel.GetFileAFSAsync(username, password);
        }
        
        public CSM.Service.Messages.SchedTask.ExportAFSTaskResponse ExportFileAFS(string username, string password) {
            return base.Channel.ExportFileAFS(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ExportAFSTaskResponse> ExportFileAFSAsync(string username, string password) {
            return base.Channel.ExportFileAFSAsync(username, password);
        }
        
        public CSM.Service.Messages.SchedTask.ExportNCBTaskResponse ExportFileNCB(string username, string password) {
            return base.Channel.ExportFileNCB(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ExportNCBTaskResponse> ExportFileNCBAsync(string username, string password) {
            return base.Channel.ExportFileNCBAsync(username, password);
        }
        
        public CSM.Service.Messages.SchedTask.ImportBDWTaskResponse GetFileBDW(string username, string password, bool skipSftp) {
            return base.Channel.GetFileBDW(username, password, skipSftp);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportBDWTaskResponse> GetFileBDWAsync(string username, string password, bool skipSftp) {
            return base.Channel.GetFileBDWAsync(username, password, skipSftp);
        }
        
        public CSM.Service.Messages.SchedTask.ImportCISTaskResponse GetFileCIS(string username, string password) {
            return base.Channel.GetFileCIS(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportCISTaskResponse> GetFileCISAsync(string username, string password) {
            return base.Channel.GetFileCISAsync(username, password);
        }
        
        public CSM.Service.Messages.SchedTask.ImportHpTaskResponse GetFileHP(string username, string password) {
            return base.Channel.GetFileHP(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportHpTaskResponse> GetFileHPAsync(string username, string password) {
            return base.Channel.GetFileHPAsync(username, password);
        }
        
        public CSM.Service.Messages.SchedTask.ImportHRTaskResponse GetFileHR(string username, string password) {
            return base.Channel.GetFileHR(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.ImportHRTaskResponse> GetFileHRAsync(string username, string password) {
            return base.Channel.GetFileHRAsync(username, password);
        }
    }
}
