//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNCContext : DbContext
    {
        public DNCContext()
            : base("name=DNCContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_C_DNC_TIME_PERIOD> TB_C_DNC_TIME_PERIOD { get; set; }
        public virtual DbSet<TB_L_DNC_ACTION_LOG> TB_L_DNC_ACTION_LOG { get; set; }
        public virtual DbSet<TB_T_DNC_ACTIVITY_PRODUCT> TB_T_DNC_ACTIVITY_PRODUCT { get; set; }
        public virtual DbSet<TB_T_DNC_ACTIVITY_TYPE> TB_T_DNC_ACTIVITY_TYPE { get; set; }
        public virtual DbSet<TB_T_DNC_EMAIL> TB_T_DNC_EMAIL { get; set; }
        public virtual DbSet<TB_T_DNC_EXPORT_FLAG> TB_T_DNC_EXPORT_FLAG { get; set; }
        public virtual DbSet<TB_T_DNC_LOAD_LIST> TB_T_DNC_LOAD_LIST { get; set; }
        public virtual DbSet<TB_T_DNC_LOAD_LIST_DATA> TB_T_DNC_LOAD_LIST_DATA { get; set; }
        public virtual DbSet<TB_T_DNC_PHONE_NO> TB_T_DNC_PHONE_NO { get; set; }
        public virtual DbSet<TB_T_DNC_TRANSACTION> TB_T_DNC_TRANSACTION { get; set; }
        public virtual DbSet<TB_T_DNC_TRANSACTION_HIS> TB_T_DNC_TRANSACTION_HIS { get; set; }
        public virtual DbSet<TB_T_DNC_TRANSACTION_HIS_EMAIL> TB_T_DNC_TRANSACTION_HIS_EMAIL { get; set; }
        public virtual DbSet<TB_T_DNC_TRANSACTION_HIS_PHONE> TB_T_DNC_TRANSACTION_HIS_PHONE { get; set; }
        public virtual DbSet<TB_T_DNC_TRANSACTION_HIS_PRODUCT> TB_T_DNC_TRANSACTION_HIS_PRODUCT { get; set; }
    }
}
