//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    
    public partial class SP_GET_SR_ACTIVITY_Result1
    {
        public int SR_ACTIVITY_ID { get; set; }
        public int SR_ID { get; set; }
        public string SR_NO { get; set; }
        public string SR_CALL_ID { get; set; }
        public string SR_ANO { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> CUSTOMER_SUBSCRIPT_TYPE_ID { get; set; }
        public string CUSTOMER_SUBSCRIPT_TYPE_NAME { get; set; }
        public string CUSTOMER_SUBSCRIPT_TYPE_CODE { get; set; }
        public string CUSTOMER_CARD_NO { get; set; }
        public Nullable<System.DateTime> CUSTOMER_BIRTH_DATE { get; set; }
        public string CUSTOMER_TITLE_NAME_TH { get; set; }
        public string CUSTOMER_FIRST_NAME_TH { get; set; }
        public string CUSTOMER_LAST_NAME_TH { get; set; }
        public string CUSTOMER_TITLE_NAME_EN { get; set; }
        public string CUSTOMER_FIRST_NAME_EN { get; set; }
        public string CUSTOMER_LAST_NAME_EN { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public string CUSTOMER_EMPLOYEE_CODE { get; set; }
        public string CUSTOMER_KKCIS_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string ACCOUNT_CAR_NO { get; set; }
        public string ACCOUNT_PRODUCT_GROUP { get; set; }
        public string ACCOUNT_PRODUCT { get; set; }
        public string ACCOUNT_BRANCH_NAME { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public string CONTACT_SUBSCRIPT_TYPE_NAME { get; set; }
        public string CONTACT_CARD_NO { get; set; }
        public Nullable<System.DateTime> CONTACT_BIRTH_DATE { get; set; }
        public string CONTACT_TITLE_NAME_TH { get; set; }
        public string CONTACT_FIRST_NAME_TH { get; set; }
        public string CONTACT_LAST_NAME_TH { get; set; }
        public string CONTACT_TITLE_NAME_EN { get; set; }
        public string CONTACT_FIRST_NAME_EN { get; set; }
        public string CONTACT_LAST_NAME_EN { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string CONTACT_ACCOUNT_NO { get; set; }
        public string CONTACT_RELATIONSHIP_NAME { get; set; }
        public string PRODUCTGROUP_CODE { get; set; }
        public string PRODUCTGROUP_NAME { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string CAMPAIGNSERVICE_CODE { get; set; }
        public string CAMPAIGNSERVICE_NAME { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<decimal> AREA_CODE { get; set; }
        public string AREA_NAME { get; set; }
        public Nullable<int> SUBAREA_ID { get; set; }
        public Nullable<decimal> SUBAREA_CODE { get; set; }
        public string SUBAREA_NAME { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<decimal> TYPE_CODE { get; set; }
        public string TYPE_NAME { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string CHANNEL_NAME { get; set; }
        public string MEDIA_SOURCE_NAME { get; set; }
        public string SR_SUBJECT { get; set; }
        public string SR_REMARK { get; set; }
        public string SR_IS_VERIFY { get; set; }
        public string SR_IS_VERIFY_PASS { get; set; }
        public Nullable<int> SR_PAGE_ID { get; set; }
        public string CREATE_BRANCH_NAME { get; set; }
        public string CREATE_FIRST_NAME { get; set; }
        public string CREATE_LAST_NAME { get; set; }
        public string CREATE_POSITION_CODE { get; set; }
        public string OWNER_BRANCH_NAME { get; set; }
        public string OWNER_FIRST_NAME { get; set; }
        public string OWNER_LAST_NAME { get; set; }
        public string OWNER_POSITION_CODE { get; set; }
        public string DELEGATE_BRANCH_NAME { get; set; }
        public string DELEGATE_FIRST_NAME { get; set; }
        public string DELEGATE_LAST_NAME { get; set; }
        public string DELEGATE_POSITION_CODE { get; set; }
        public string SR_EMAIL_TEMPLATE_ID { get; set; }
        public string SR_ACTIVITY_EMAIL_SENDER { get; set; }
        public string SR_ACTIVITY_EMAIL_TO { get; set; }
        public string SR_ACTIVITY_EMAIL_CC { get; set; }
        public string SR_ACTIVITY_EMAIL_SUBJECT { get; set; }
        public string SR_ACTIVITY_EMAIL_BODY { get; set; }
        public string SR_ACTIVITY_EMAIL_ATTACHMENTS { get; set; }
        public string SR_ACTIVITY_DESC { get; set; }
        public Nullable<int> SR_ACTIVITY_TYPE_ID { get; set; }
        public string SR_ACTIVITY_TYPE_NAME { get; set; }
        public string SR_STATUS_NAME { get; set; }
        public string SR_DEF_ADDRESS_HOUSE_NO { get; set; }
        public string SR_DEF_ADDRESS_VILLAGE { get; set; }
        public string SR_DEF_ADDRESS_BUILDING { get; set; }
        public string SR_DEF_ADDRESS_FLOOR_NO { get; set; }
        public string SR_DEF_ADDRESS_ROOM_NO { get; set; }
        public string SR_DEF_ADDRESS_MOO { get; set; }
        public string SR_DEF_ADDRESS_SOI { get; set; }
        public string SR_DEF_ADDRESS_STREET { get; set; }
        public string SR_DEF_ADDRESS_TAMBOL { get; set; }
        public string SR_DEF_ADDRESS_AMPHUR { get; set; }
        public string SR_DEF_ADDRESS_PROVINCE { get; set; }
        public string SR_DEF_ADDRESS_ZIPCODE { get; set; }
        public string SR_AFS_ASSET_NO { get; set; }
        public string SR_AFS_ASSET_DESC { get; set; }
        public Nullable<System.DateTime> SR_NCB_CUSTOMER_BIRTHDATE { get; set; }
        public string SR_NCB_CHECK_STATUS { get; set; }
        public string SR_NCB_MARKETING_FULL_NAME { get; set; }
        public string SR_NCB_MARKETING_BRANCH_NAME { get; set; }
        public string SR_NCB_MARKETING_BRANCH_UPPER_1_NAME { get; set; }
        public string SR_NCB_MARKETING_BRANCH_UPPER_2_NAME { get; set; }
        public Nullable<System.DateTime> ACTIVITY_CREATE_DATE { get; set; }
        public string ACTIVITY_CREATE_FIRST_NAME { get; set; }
        public string ACTIVITY_CREATE_LAST_NAME { get; set; }
        public string ACTIVITY_CREATE_POSITION_CODE { get; set; }
        public string ACTIVITY_CREATE_EMPLOYEE_CODE { get; set; }
        public Nullable<int> MAP_PRODUCT_ID { get; set; }
        public string HP_SUBJECT { get; set; }
        public string HP_LANGUAGE_INDEPENDENT_CODE { get; set; }
        public string SR_ACTIVITY_EMAIL_BCC { get; set; }
        public string CPN_PRODUCTGROUP_NAME { get; set; }
        public string CPN_PRODUCT_NAME { get; set; }
        public string CPN_CAMPAIGNSERVICE_NAME { get; set; }
        public string CPN_SUBJECT_NAME { get; set; }
        public string CPN_TYPE_NAME { get; set; }
        public string CPN_ROOTCAUSE_NAME { get; set; }
        public string CPN_ISSUES_NAME { get; set; }
        public Nullable<bool> CPN_SECRET { get; set; }
        public Nullable<bool> CPN_CAR { get; set; }
        public Nullable<bool> CPN_HPLog100 { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public string CPN_BUGROUP_NAME { get; set; }
        public Nullable<bool> CPN_SUMMARY { get; set; }
        public Nullable<bool> CPN_CAUSE_CUSTOMER { get; set; }
        public string CPN_CAUSE_CUSTOMER_DETAIL { get; set; }
        public Nullable<bool> CPN_CAUSE_STAFF { get; set; }
        public string CPN_CAUSE_STAFF_DETAIL { get; set; }
        public Nullable<bool> CPN_CAUSE_SYSTEM { get; set; }
        public string CPN_CAUSE_SYSTEM_DETAIL { get; set; }
        public Nullable<bool> CPN_CAUSE_PROCESS { get; set; }
        public string CPN_CAUSE_PROCESS_DETAIL { get; set; }
        public string CPN_CAUSE_NAME { get; set; }
        public string CPN_SUMMARY_NAME { get; set; }
        public string CPN_FIXED_DETAIL { get; set; }
        public string CPN_BU1_CODE { get; set; }
        public string CPN_BU1DESC { get; set; }
        public string CPN_BU2_CODE { get; set; }
        public string CPN_BU2DESC { get; set; }
        public string CPN_BU3_CODE { get; set; }
        public string CPN_BU3DESC { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public string BRANCH_NAME { get; set; }
        public string SR_STATE_NAME { get; set; }
    }
}
