//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_RULE_OPTION
    {
        public int RULE_OPTION_ID { get; set; }
        public string OPTION_CODE { get; set; }
        public string OPTION_DESC { get; set; }
        public string OPTION_TYPE { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string OPTION_SUB_CODE { get; set; }
        public string OPTION_CREATE_BY { get; set; }
        public bool IS_DELETE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string SYSTEM_VIEW { get; set; }
    }
}
