//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_SCREEN
    {
        public TB_C_SCREEN()
        {
            this.TB_C_ROLE_SCREEN = new HashSet<TB_C_ROLE_SCREEN>();
        }
    
        public int SCREEN_ID { get; set; }
        public Nullable<int> MENU_ID { get; set; }
        public string SCREEN_NAME { get; set; }
        public string SCREEN_CODE { get; set; }
        public string ACTION_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
    
        public virtual TB_C_MENU TB_C_MENU { get; set; }
        public virtual ICollection<TB_C_ROLE_SCREEN> TB_C_ROLE_SCREEN { get; set; }
    }
}
