//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_DNC_TIME_PERIOD
    {
        public int TIME_PERIOD_ID { get; set; }
        public string TIME_PERIOD_FROM { get; set; }
        public string TIME_PERIOD_TO { get; set; }
        public string EXECUTE_TIME { get; set; }
    }
}
