//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_ROLE
    {
        public TB_C_ROLE()
        {
            this.TB_C_ROLE_SR_PAGE = new HashSet<TB_C_ROLE_SR_PAGE>();
            this.TB_M_CONFIG_ROLE = new HashSet<TB_M_CONFIG_ROLE>();
        }
    
        public int ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_CODE { get; set; }
        public Nullable<int> ROLE_VALUE { get; set; }
    
        public virtual ICollection<TB_C_ROLE_SR_PAGE> TB_C_ROLE_SR_PAGE { get; set; }
        public virtual ICollection<TB_M_CONFIG_ROLE> TB_M_CONFIG_ROLE { get; set; }
    }
}
