//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_SR_STATUS_CHANGE
    {
        public int SR_STATUS_CHANGE_ID { get; set; }
        public int FROM_SR_STATUS_ID { get; set; }
        public int TO_SR_STATUS_ID { get; set; }
        public Nullable<int> PRODUCTGROUP_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> CAMPAIGNSERVICE_ID { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> SUBAREA_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
    
        public virtual TB_C_SR_STATUS TB_C_SR_STATUS { get; set; }
        public virtual TB_C_SR_STATUS TB_C_SR_STATUS1 { get; set; }
        public virtual TB_M_AREA TB_M_AREA { get; set; }
        public virtual TB_M_SUBAREA TB_M_SUBAREA { get; set; }
        public virtual TB_M_TYPE TB_M_TYPE { get; set; }
        public virtual TB_R_CAMPAIGNSERVICE TB_R_CAMPAIGNSERVICE { get; set; }
        public virtual TB_R_PRODUCT TB_R_PRODUCT { get; set; }
        public virtual TB_R_PRODUCTGROUP TB_R_PRODUCTGROUP { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
    }
}
