//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_SEQ_SEND_OTP
    {
        public int SEQ_SEND_OTP_ID { get; set; }
        public Nullable<System.DateTime> CURR_DATE { get; set; }
    }
}
