//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_MENU
    {
        public TB_C_MENU()
        {
            this.TB_M_CONFIG_URL = new HashSet<TB_M_CONFIG_URL>();
            this.TB_C_SCREEN = new HashSet<TB_C_SCREEN>();
        }
    
        public int MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_CODE { get; set; }
        public string ACTION_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string CSS_CLASS { get; set; }
    
        public virtual ICollection<TB_M_CONFIG_URL> TB_M_CONFIG_URL { get; set; }
        public virtual ICollection<TB_C_SCREEN> TB_C_SCREEN { get; set; }
    }
}
