//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_SUBSCRIPTION
    {
        public int SUBSCRIPTION_ID { get; set; }
        public string KKCIS_ID { get; set; }
        public string CUST_ID { get; set; }
        public string CARD_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string PROD_GROUP { get; set; }
        public string PROD_TYPE { get; set; }
        public string SUBSCR_CODE { get; set; }
        public string REF_NO { get; set; }
        public string TEXT1 { get; set; }
        public string TEXT2 { get; set; }
        public string TEXT3 { get; set; }
        public string TEXT4 { get; set; }
        public string TEXT5 { get; set; }
        public string TEXT6 { get; set; }
        public string TEXT7 { get; set; }
        public string TEXT8 { get; set; }
        public string TEXT9 { get; set; }
        public string TEXT10 { get; set; }
        public string NUMBER1 { get; set; }
        public string NUMBER2 { get; set; }
        public string NUMBER3 { get; set; }
        public string NUMBER4 { get; set; }
        public string NUMBER5 { get; set; }
        public string DATE1 { get; set; }
        public string DATE2 { get; set; }
        public string DATE3 { get; set; }
        public string DATE4 { get; set; }
        public string DATE5 { get; set; }
        public string SUBSCR_STATUS { get; set; }
        public string CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public string CREATE_CHANNEL { get; set; }
        public string UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string ERROR { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string UPDATED_CHANNEL { get; set; }
        public string BRANCH_NAME { get; set; }
        public string SYSCUSTSUBSCR_ID { get; set; }
    }
}
