//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_PRODUCT_GROUP
    {
        public int PRODUCT_GROUP_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string PRODUCT_DESC { get; set; }
        public string SYSTEM { get; set; }
        public string PRODUCT_FLAG { get; set; }
        public string ENTITY_CODE { get; set; }
        public string SUBSCR_CODE { get; set; }
        public string SUBSCR_DESC { get; set; }
        public string STATUS { get; set; }
    }
}
