//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_SALE_ZONE
    {
        public int SALE_ZONE_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string AMPHUR { get; set; }
        public string PROVINCE { get; set; }
        public string SALE_NAME { get; set; }
        public string PHONE_NO { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string ERROR { get; set; }
    
        public virtual TB_R_USER TB_R_USER { get; set; }
    }
}
