//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_HR_EMPLOYEE
    {
        public int HR_EMPLOYEE_ID { get; set; }
        public string BRANCH { get; set; }
        public string BRANCHDESC { get; set; }
        public string EMPLOYEEID { get; set; }
        public string TITLEID { get; set; }
        public string TTITLE { get; set; }
        public string TFNAME { get; set; }
        public string TLNAME { get; set; }
        public string NICKNAME { get; set; }
        public string XENGNAME { get; set; }
        public string ETITLE { get; set; }
        public string EFNAME { get; set; }
        public string ELNAME { get; set; }
        public string SEX { get; set; }
        public string BIRTHDAY { get; set; }
        public string EMPTYPE { get; set; }
        public string EMPTYPEDESC { get; set; }
        public string POSITION { get; set; }
        public string POSITONDESC { get; set; }
        public string BU1 { get; set; }
        public string BU1DESC { get; set; }
        public string BU2 { get; set; }
        public string BU2DESC { get; set; }
        public string BU3 { get; set; }
        public string BU3DESC { get; set; }
        public string BU4 { get; set; }
        public string BU4DESC { get; set; }
        public string JOB { get; set; }
        public string JOBPOSITION { get; set; }
        public string STARTDATE { get; set; }
        public string FIRSTHIREDATE { get; set; }
        public string RESIGNDATE { get; set; }
        public string STATUS { get; set; }
        public string EMPSTATUS { get; set; }
        public string EMAIL { get; set; }
        public string NOTESADDRESS { get; set; }
        public string WORKAREA { get; set; }
        public string WORKAREADESC { get; set; }
        public string COSTCENTER { get; set; }
        public string COSTCENTERDESC { get; set; }
        public string TELEXT { get; set; }
        public string BOSS { get; set; }
        public string BOSSNAME { get; set; }
        public string ASSESSOR1 { get; set; }
        public string ASSESSOR1NAME { get; set; }
        public string ASSESSOR2 { get; set; }
        public string ASSESSOR2NAME { get; set; }
        public string ASSESSOR3 { get; set; }
        public string ASSESSOR3NAME { get; set; }
        public string TELNO { get; set; }
        public string MOBILENO { get; set; }
        public string ADUSER { get; set; }
        public string OFFICER_ID { get; set; }
        public string OFFICER_DESC { get; set; }
        public string ADDITIONJOB { get; set; }
        public string UNITBOSS { get; set; }
        public string UNITBOSSNAME { get; set; }
        public string IDNO { get; set; }
        public string ERROR { get; set; }
    }
}
