//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_BDW_CONTACT
    {
        public int BDW_CONTACT_ID { get; set; }
        public string CARD_NO { get; set; }
        public string TITILE_TH { get; set; }
        public string NAME_TH { get; set; }
        public string SURNAME_TH { get; set; }
        public string TITILE_EN { get; set; }
        public string NAME_EN { get; set; }
        public string SURNAME_EN { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string PRODUCT_GROUP { get; set; }
        public string PRODUCT { get; set; }
        public string RELATIONSHIP { get; set; }
        public string PHONE { get; set; }
        public string CAMPAIGN { get; set; }
        public string ERROR { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public Nullable<int> CUSTOMER_CONTACT_ID { get; set; }
        public Nullable<int> RELATION_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public string DATA_TYPE { get; set; }
        public string DATA_DATE { get; set; }
        public string DATA_SOURCE { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string LOAN_MAIN { get; set; }
        public string RELATION_NAME { get; set; }
        public string MAP_CARD_TYPE_CODE { get; set; }
    }
}
