//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_SUBDISTRICT
    {
        public int CIS_SUBDISTRICT_ID { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string SUBDISTRICT_CODE { get; set; }
        public string SUBDISTRICT_NAME_TH { get; set; }
        public string SUBDISTRICT_NAME_EN { get; set; }
        public string POSTCODE { get; set; }
        public string STATUS { get; set; }
    }
}
