//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_PHONE_TYPE
    {
        public int CIS_PHONE_TYPE_ID { get; set; }
        public string PHONE_TYPE_CODE { get; set; }
        public string PHONE_TYPE_DESC { get; set; }
        public string ERROR { get; set; }
        public string STATUS { get; set; }
    }
}
