//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_TITLE
    {
        public int CIS_TITLE_ID { get; set; }
        public string TITLE_ID { get; set; }
        public string TITLE_NAME_TH { get; set; }
        public string TITLE_NAME_EN { get; set; }
        public string TITLE_TYPE_GROUP { get; set; }
        public string GENDER_CODE { get; set; }
        public string STATUS { get; set; }
    }
}
