//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_CORPORATE
    {
        public int CIS_CUSTOMER_ID { get; set; }
        public string KKCIS_ID { get; set; }
        public string CUST_ID { get; set; }
        public string CARD_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string CUST_TYPE_CODE { get; set; }
        public string CUST_TYPE_GROUP { get; set; }
        public string TITLE_ID { get; set; }
        public string NAME_TH { get; set; }
        public string NAME_EN { get; set; }
        public string ISIC_CODE { get; set; }
        public string TAX_ID { get; set; }
        public string HOST_BUSINESS_COUNTRY_CODE { get; set; }
        public string VALUE_PER_SHARE { get; set; }
        public string AUTHORIZED_SHARE_CAPITAL { get; set; }
        public string REGISTER_DATE { get; set; }
        public string BUSINESS_CODE { get; set; }
        public string FIXED_ASSET { get; set; }
        public string FIXED_ASSET_EXCLUDE_LAND { get; set; }
        public string NUMBER_OF_EMPLOYEE { get; set; }
        public string SHARE_INFO_FLAG { get; set; }
        public string FLG_MST_APP { get; set; }
        public string FIRST_BRANCH { get; set; }
        public string PLACE_CUST_UPDATED { get; set; }
        public string DATE_CUST_UPDATED { get; set; }
        public string ID_COUNTRY_ISSUE { get; set; }
        public string BUSINESS_CAT_CODE { get; set; }
        public string MARKETING_ID { get; set; }
        public string STOCK { get; set; }
        public string CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public string UPDATE_DATE { get; set; }
        public string ERROR { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> TITLE_TH_ID { get; set; }
        public Nullable<int> TITLE_EN_ID { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
    }
}
