//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_CUSTOMER_EMAIL
    {
        public int CIS_EMAIL_ID { get; set; }
        public string KKCIS_ID { get; set; }
        public string CUST_ID { get; set; }
        public string CARD_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string CUST_TYPE_GROUP { get; set; }
        public string MAIL_TYPE_CODE { get; set; }
        public string MAILACCOUNT { get; set; }
        public string CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public string UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string ERROR { get; set; }
    }
}
