//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_SUBSCRIPTION_TYPE
    {
        public int SUBSCRIPTION_TYPE_ID { get; set; }
        public string CUST_TYPE_GROUP { get; set; }
        public string CUST_TYPE_CODE { get; set; }
        public string CUST_TYPE_TH { get; set; }
        public string CUST_TYPE_EN { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string CARD_TYPE_EN { get; set; }
        public string CARD_TYPE_TH { get; set; }
        public string ERROR { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
        public string STATUS { get; set; }
    }
}
