//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_INDIVIDUAL
    {
        public int CIS_CUSTOMER_ID { get; set; }
        public string KKCIS_ID { get; set; }
        public string CUST_ID { get; set; }
        public string CARD_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string CUST_TYPE_CODE { get; set; }
        public string CUST_TYPE_GROUP { get; set; }
        public string TITLE_ID { get; set; }
        public string TITLE_NAME_CUSTOM { get; set; }
        public string FIRST_NAME_TH { get; set; }
        public string MID_NAME_TH { get; set; }
        public string LAST_NAME_TH { get; set; }
        public string FIRST_NAME_EN { get; set; }
        public string MID_NAME_EN { get; set; }
        public string LAST_NAME_EN { get; set; }
        public string BIRTH_DATE { get; set; }
        public string GENDER_CODE { get; set; }
        public string MARITAL_CODE { get; set; }
        public string NATIONALITY1_CODE { get; set; }
        public string NATIONALITY2_CODE { get; set; }
        public string NATIONALITY3_CODE { get; set; }
        public string RELIGION_CODE { get; set; }
        public string EDUCATION_CODE { get; set; }
        public string POSITION { get; set; }
        public string BUSINESS_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string ISIC_CODE { get; set; }
        public string ANNUAL_INCOME { get; set; }
        public string SOURCE_INCOME { get; set; }
        public string TOTAL_WEALTH_PERIOD { get; set; }
        public string FLG_MST_APP { get; set; }
        public string CHANNEL_HOME { get; set; }
        public string FIRST_BRANCH { get; set; }
        public string SHARE_INFO_FLAG { get; set; }
        public string PLACE_CUST_UPDATED { get; set; }
        public string DATE_CUST_UPDATED { get; set; }
        public string ANNUAL_INCOME_PERIOD { get; set; }
        public string MARKETING_ID { get; set; }
        public string NUMBER_OF_EMPLOYEE { get; set; }
        public string FIXED_ASSET { get; set; }
        public string FIXED_ASSET_EXCLUDE_LAND { get; set; }
        public string OCCUPATION_CODE { get; set; }
        public string OCCUPATION_SUBTYPE_CODE { get; set; }
        public string COUNTRY_INCOME { get; set; }
        public string TOTAL_WEALTH { get; set; }
        public string SOURCE_INCOME_REM { get; set; }
        public string CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public string UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public string ERROR { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> TITLE_TH_ID { get; set; }
        public Nullable<int> TITLE_EN_ID { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
    }
}
