//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_L_SR_LOGGING
    {
        public int SR_LOGGING_ID { get; set; }
        public int SR_ID { get; set; }
        public Nullable<int> SR_ACTIVITY_ID { get; set; }
        public string SR_LOGGING_SYSTEM_ACTION { get; set; }
        public string SR_LOGGING_ACTION { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> SR_STATUS_ID_OLD { get; set; }
        public Nullable<int> SR_STATUS_ID_NEW { get; set; }
        public Nullable<int> OWNER_USER_ID_OLD { get; set; }
        public Nullable<int> OWNER_USER_ID_NEW { get; set; }
        public Nullable<int> DELEGATE_USER_ID_OLD { get; set; }
        public Nullable<int> DELEGATE_USER_ID_NEW { get; set; }
        public Nullable<int> OVER_SLA_MINUTE { get; set; }
        public Nullable<int> OVER_SLA_TIMES { get; set; }
        public Nullable<int> WORKING_MINUTE { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<int> INT_ID_OLD { get; set; }
        public Nullable<int> INT_ID_NEW { get; set; }
        public Nullable<bool> BIT_VALUE_OLD { get; set; }
        public Nullable<bool> BIT_VALUE_NEW { get; set; }
        public Nullable<int> WORKING_HOUR { get; set; }
    
        public virtual TB_C_SR_STATUS TB_C_SR_STATUS { get; set; }
        public virtual TB_C_SR_STATUS TB_C_SR_STATUS1 { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
        public virtual TB_R_USER TB_R_USER2 { get; set; }
        public virtual TB_R_USER TB_R_USER3 { get; set; }
        public virtual TB_T_SR TB_T_SR { get; set; }
    }
}
