//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_L_DNC_ACTION_LOG
    {
        public int DNC_ACTION_LOG_ID { get; set; }
        public string ACTION { get; set; }
        public string STATUS { get; set; }
        public string DETAIL { get; set; }
        public string FROM_SYSTEM { get; set; }
        public string MODULE { get; set; }
        public string IP_ADDRESS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_USER { get; set; }
        public Nullable<int> DNC_TRANSACTION_ID { get; set; }
    }
}
