//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_L_LOGIN
    {
        public int LOGIN_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string SESSION_ID { get; set; }
        public Nullable<short> LOGGED_IN { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
