//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_MAP_PRODUCT
    {
        public TB_M_MAP_PRODUCT()
        {
            this.TB_M_MAP_PRODUCT_QUESTIONGROUP = new HashSet<TB_M_MAP_PRODUCT_QUESTIONGROUP>();
            this.TB_T_SR = new HashSet<TB_T_SR>();
        }
    
        public int MAP_PRODUCT_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<int> CAMPAIGNSERVICE_ID { get; set; }
        public int AREA_ID { get; set; }
        public Nullable<int> SUBAREA_ID { get; set; }
        public int TYPE_ID { get; set; }
        public Nullable<int> DEFAULT_OWNER_USER_ID { get; set; }
        public int SR_PAGE_ID { get; set; }
        public bool MAP_PRODUCT_IS_VERIFY { get; set; }
        public bool MAP_PRODUCT_IS_ACTIVE { get; set; }
        public string HP_SUBJECT { get; set; }
        public string HP_LANGUAGE_INDEPENDENT_CODE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public bool IS_VERIFY_OTP { get; set; }
        public bool IS_SR_SECRET { get; set; }
        public Nullable<int> OTP_TEMPLATE_ID { get; set; }
    
        public virtual TB_C_SR_PAGE TB_C_SR_PAGE { get; set; }
        public virtual TB_M_AREA TB_M_AREA { get; set; }
        public virtual ICollection<TB_M_MAP_PRODUCT_QUESTIONGROUP> TB_M_MAP_PRODUCT_QUESTIONGROUP { get; set; }
        public virtual TB_M_SUBAREA TB_M_SUBAREA { get; set; }
        public virtual TB_M_TYPE TB_M_TYPE { get; set; }
        public virtual TB_R_CAMPAIGNSERVICE TB_R_CAMPAIGNSERVICE { get; set; }
        public virtual TB_R_PRODUCT TB_R_PRODUCT { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
        public virtual TB_R_USER TB_R_USER2 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
    }
}
