//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_DOCUMENT_TYPE
    {
        public TB_M_DOCUMENT_TYPE()
        {
            this.TB_T_ATTACHMENT_TYPE = new HashSet<TB_T_ATTACHMENT_TYPE>();
            this.TB_T_SR_ATTACHMENT_DOCUMENT_TYPE = new HashSet<TB_T_SR_ATTACHMENT_DOCUMENT_TYPE>();
        }
    
        public int DOCUMENT_TYPE_ID { get; set; }
        public string DOCUMENT_TYPE_CODE { get; set; }
        public string DOCUMENT_TYPE_NAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> CATEGORY { get; set; }
    
        public virtual ICollection<TB_T_ATTACHMENT_TYPE> TB_T_ATTACHMENT_TYPE { get; set; }
        public virtual ICollection<TB_T_SR_ATTACHMENT_DOCUMENT_TYPE> TB_T_SR_ATTACHMENT_DOCUMENT_TYPE { get; set; }
    }
}
