//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_TITLE
    {
        public TB_M_TITLE()
        {
            this.TB_M_CONTACT = new HashSet<TB_M_CONTACT>();
            this.TB_M_CONTACT1 = new HashSet<TB_M_CONTACT>();
            this.TB_M_CUSTOMER = new HashSet<TB_M_CUSTOMER>();
            this.TB_M_CUSTOMER1 = new HashSet<TB_M_CUSTOMER>();
        }
    
        public int TITLE_ID { get; set; }
        public string TITLE_NAME { get; set; }
        public string LANGUAGE { get; set; }
    
        public virtual ICollection<TB_M_CONTACT> TB_M_CONTACT { get; set; }
        public virtual ICollection<TB_M_CONTACT> TB_M_CONTACT1 { get; set; }
        public virtual ICollection<TB_M_CUSTOMER> TB_M_CUSTOMER { get; set; }
        public virtual ICollection<TB_M_CUSTOMER> TB_M_CUSTOMER1 { get; set; }
    }
}
