//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_COMPLAINT_MAPPING
    {
        public int MAPPING_ID { get; set; }
        public Nullable<int> COMPLAINT_SUBJECT_ID { get; set; }
        public Nullable<int> COMPLAINT_TYPE_ID { get; set; }
        public Nullable<int> ROOT_CAUSE_ID { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
