//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_QUESTIONGROUP_QUESTION
    {
        public int QUESTIONGROUP_QUESTION_ID { get; set; }
        public int QUESTIONGROUP_ID { get; set; }
        public int QUESTION_ID { get; set; }
        public int SEQ_NO { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual TB_M_QUESTION TB_M_QUESTION { get; set; }
        public virtual TB_M_QUESTIONGROUP TB_M_QUESTIONGROUP { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
    }
}
