//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_SLA
    {
        public int SLA_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<int> CAMPAIGNSERVICE_ID { get; set; }
        public int AREA_ID { get; set; }
        public Nullable<int> SUBAREA_ID { get; set; }
        public int TYPE_ID { get; set; }
        public int CHANNEL_ID { get; set; }
        public int SR_STATUS_ID { get; set; }
        public int SLA_MINUTE { get; set; }
        public int SLA_TIMES { get; set; }
        public int SLA_DAY { get; set; }
        public bool SLA_IS_ACTIVE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> ALERT_CHIEF_TIMES { get; set; }
        public Nullable<int> ALERT_CHIEF1_TIMES { get; set; }
        public Nullable<int> ALERT_CHIEF2_TIMES { get; set; }
        public Nullable<int> ALERT_CHIEF3_TIMES { get; set; }
    
        public virtual TB_C_SR_STATUS TB_C_SR_STATUS { get; set; }
        public virtual TB_M_AREA TB_M_AREA { get; set; }
        public virtual TB_M_SUBAREA TB_M_SUBAREA { get; set; }
        public virtual TB_M_TYPE TB_M_TYPE { get; set; }
        public virtual TB_R_CAMPAIGNSERVICE TB_R_CAMPAIGNSERVICE { get; set; }
        public virtual TB_R_CHANNEL TB_R_CHANNEL { get; set; }
        public virtual TB_R_PRODUCT TB_R_PRODUCT { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
    }
}
