//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_CUSTOMER_CONTACT
    {
        public int CUSTOMER_CONTACT_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public Nullable<int> RELATIONSHIP_ID { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_EDIT { get; set; }
        public string SYSTEM { get; set; }
    
        public virtual TB_M_ACCOUNT TB_M_ACCOUNT { get; set; }
        public virtual TB_M_CONTACT TB_M_CONTACT { get; set; }
        public virtual TB_M_CUSTOMER TB_M_CUSTOMER { get; set; }
        public virtual TB_M_RELATIONSHIP TB_M_RELATIONSHIP { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
    }
}
