//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_MEDIA_SOURCE
    {
        public TB_M_MEDIA_SOURCE()
        {
            this.TB_T_SR = new HashSet<TB_T_SR>();
        }
    
        public int MEDIA_SOURCE_ID { get; set; }
        public string MEDIA_SOURCE_NAME { get; set; }
    
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
    }
}
