//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_QUESTIONGROUP
    {
        public TB_M_QUESTIONGROUP()
        {
            this.TB_M_MAP_PRODUCT_QUESTIONGROUP = new HashSet<TB_M_MAP_PRODUCT_QUESTIONGROUP>();
            this.TB_T_SR_VERIFY_RESULT_GROUP = new HashSet<TB_T_SR_VERIFY_RESULT_GROUP>();
            this.TB_M_QUESTIONGROUP_QUESTION = new HashSet<TB_M_QUESTIONGROUP_QUESTION>();
        }
    
        public int QUESTIONGROUP_ID { get; set; }
        public string QUESTIONGROUP_NAME { get; set; }
        public Nullable<bool> QUESTIONGROUP_IS_ACTIVE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int PRODUCT_ID { get; set; }
        public string QUESTIONGROUP_DESC { get; set; }
    
        public virtual ICollection<TB_M_MAP_PRODUCT_QUESTIONGROUP> TB_M_MAP_PRODUCT_QUESTIONGROUP { get; set; }
        public virtual ICollection<TB_T_SR_VERIFY_RESULT_GROUP> TB_T_SR_VERIFY_RESULT_GROUP { get; set; }
        public virtual ICollection<TB_M_QUESTIONGROUP_QUESTION> TB_M_QUESTIONGROUP_QUESTION { get; set; }
        public virtual TB_R_PRODUCT TB_R_PRODUCT { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
    }
}
