//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_HR_EMPLOYEE
    {
        public int EMP_ID { get; set; }
        public string EMPLOYEEID { get; set; }
        public string TFNAME { get; set; }
        public string TLNAME { get; set; }
        public string EMAIL { get; set; }
        public string BOSS { get; set; }
        public string BOSSNAME { get; set; }
        public string BOSS_EMAIL { get; set; }
        public string ASSESSOR1 { get; set; }
        public string ASSESSOR1NAME { get; set; }
        public string ASSESSOR1_EMAIL { get; set; }
        public string ASSESSOR2 { get; set; }
        public string ASSESSOR2NAME { get; set; }
        public string ASSESSOR2_EMAIL { get; set; }
        public string ASSESSOR3 { get; set; }
        public string ASSESSOR3NAME { get; set; }
        public string ASSESSOR3_EMAIL { get; set; }
        public string ADDITIONJOB { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
