//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_HP_STATUS
    {
        public int HP_ID { get; set; }
        public string HP_SUBJECT { get; set; }
        public string HP_LANGUAGE_INDEPENDENT_CODE { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
