//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_COMPLAINT_SUMMARY
    {
        public int COMPLAINT_SUMMARY_ID { get; set; }
        public string COMPLAINT_SUMMARY_NAME { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
