//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_POOL
    {
        public TB_M_POOL()
        {
            this.TB_M_POOL_BRANCH = new HashSet<TB_M_POOL_BRANCH>();
            this.TB_T_JOB = new HashSet<TB_T_JOB>();
        }
    
        public int POOL_ID { get; set; }
        public string POOL_NAME { get; set; }
        public string POOL_DESC { get; set; }
        public string EMAIL { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
    
        public virtual ICollection<TB_M_POOL_BRANCH> TB_M_POOL_BRANCH { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
        public virtual ICollection<TB_T_JOB> TB_T_JOB { get; set; }
    }
}
