//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_HR_BU
    {
        public int HR_BU_ID { get; set; }
        public string BU1 { get; set; }
        public string BU1DESC { get; set; }
        public string BU2 { get; set; }
        public string BU2DESC { get; set; }
        public string BU3 { get; set; }
        public string BU3DESC { get; set; }
        public string BU4 { get; set; }
        public string BU4DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
