//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ADDRESS
    {
        public int ADDRESS_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<short> ADDRESS_TYPE { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual TB_M_CUSTOMER TB_M_CUSTOMER { get; set; }
    }
}
