//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_CONFIG_URL
    {
        public TB_M_CONFIG_URL()
        {
            this.TB_M_CONFIG_ROLE = new HashSet<TB_M_CONFIG_ROLE>();
        }
    
        public int CONFIG_URL_ID { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public string CONFIG_NAME { get; set; }
        public string CONFIG_URL { get; set; }
        public string IMAGE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> MENU_ID { get; set; }
        public string FONT_NAME { get; set; }
    
        public virtual TB_C_MENU TB_C_MENU { get; set; }
        public virtual ICollection<TB_M_CONFIG_ROLE> TB_M_CONFIG_ROLE { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
    }
}
