//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_POOL_BRANCH
    {
        public int POOL_BRANCH_ID { get; set; }
        public Nullable<int> POOL_ID { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public Nullable<short> STATUS { get; set; }
    
        public virtual TB_M_POOL TB_M_POOL { get; set; }
        public virtual TB_R_BRANCH TB_R_BRANCH { get; set; }
    }
}
