//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_AFS_ASSET
    {
        public TB_M_AFS_ASSET()
        {
            this.TB_T_SR = new HashSet<TB_T_SR>();
        }
    
        public int ASSET_ID { get; set; }
        public string ASSET_NO { get; set; }
        public string ASSET_TYPE { get; set; }
        public string STATUS { get; set; }
        public string STATUS_DESC { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_DES { get; set; }
        public string AFS_REF_NO { get; set; }
        public string AMPHUR { get; set; }
        public string PROVINCE { get; set; }
        public Nullable<int> SALE_USER_ID { get; set; }
        public string SALE_NAME { get; set; }
        public string PHONE_NO { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
    }
}
