//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_MAP_AUTO_FORWARD
    {
        public int AUTO_FORWARD_ID { get; set; }
        public Nullable<int> CHANNEL_ID { get; set; }
        public int FORWARD_TO_USER { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> CAMPAIGNSERVICE_ID { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> SUBAREA_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public bool IS_VERIFY { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
