//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_CONTACT
    {
        public TB_M_CONTACT()
        {
            this.TB_M_CUSTOMER_CONTACT = new HashSet<TB_M_CUSTOMER_CONTACT>();
            this.TB_M_CONTACT_PHONE = new HashSet<TB_M_CONTACT_PHONE>();
            this.TB_T_SR = new HashSet<TB_T_SR>();
        }
    
        public int CONTACT_ID { get; set; }
        public string FIRST_NAME_TH { get; set; }
        public string LAST_NAME_TH { get; set; }
        public string FIRST_NAME_EN { get; set; }
        public string LAST_NAME_EN { get; set; }
        public string CARD_NO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
        public Nullable<int> TITLE_EN_ID { get; set; }
        public Nullable<int> TITLE_TH_ID { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<bool> IS_DEFAULT { get; set; }
        public Nullable<bool> IS_EDIT { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> KKCIS_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
    
        public virtual ICollection<TB_M_CUSTOMER_CONTACT> TB_M_CUSTOMER_CONTACT { get; set; }
        public virtual ICollection<TB_M_CONTACT_PHONE> TB_M_CONTACT_PHONE { get; set; }
        public virtual TB_M_TITLE TB_M_TITLE { get; set; }
        public virtual TB_M_TITLE TB_M_TITLE1 { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
        public virtual TB_M_SUBSCRIPT_TYPE TB_M_SUBSCRIPT_TYPE { get; set; }
    }
}
