//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ACCOUNT_PHONE
    {
        public int ACCOUNT_PHONE_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string PHONE_EXT { get; set; }
        public string PHONE_TYPE_CODE { get; set; }
        public string PHONE_TYPE_NAME { get; set; }
        public string PRODUCT_GROUP { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string SUBSCRIPTION_CODE { get; set; }
        public string UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
    
        public virtual TB_M_CUSTOMER TB_M_CUSTOMER { get; set; }
        public virtual TB_M_ACCOUNT TB_M_ACCOUNT { get; set; }
    }
}
