//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_PRODUCTGROUP
    {
        public TB_R_PRODUCTGROUP()
        {
            this.TB_C_SR_STATUS_CHANGE = new HashSet<TB_C_SR_STATUS_CHANGE>();
            this.TB_R_PRODUCT = new HashSet<TB_R_PRODUCT>();
            this.TB_T_SR = new HashSet<TB_T_SR>();
        }
    
        public int PRODUCTGROUP_ID { get; set; }
        public string PRODUCTGROUP_NAME { get; set; }
        public bool PRODUCTGROUP_IS_ACTIVE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PRODUCTGROUP_CODE { get; set; }
    
        public virtual ICollection<TB_C_SR_STATUS_CHANGE> TB_C_SR_STATUS_CHANGE { get; set; }
        public virtual ICollection<TB_R_PRODUCT> TB_R_PRODUCT { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
    }
}
