//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_BRANCH
    {
        public TB_R_BRANCH()
        {
            this.TB_M_POOL_BRANCH = new HashSet<TB_M_POOL_BRANCH>();
            this.TB_T_SR_ACTIVITY = new HashSet<TB_T_SR_ACTIVITY>();
            this.TB_T_NEWS_BRANCH = new HashSet<TB_T_NEWS_BRANCH>();
            this.TB_R_BRANCH1 = new HashSet<TB_R_BRANCH>();
            this.TB_R_BRANCH_CALENDAR = new HashSet<TB_R_BRANCH_CALENDAR>();
            this.TB_T_SR_ACTIVITY1 = new HashSet<TB_T_SR_ACTIVITY>();
            this.TB_T_SR_ACTIVITY2 = new HashSet<TB_T_SR_ACTIVITY>();
            this.TB_R_USER = new HashSet<TB_R_USER>();
            this.TB_T_SR = new HashSet<TB_T_SR>();
            this.TB_T_SR1 = new HashSet<TB_T_SR>();
            this.TB_T_SR2 = new HashSet<TB_T_SR>();
            this.TB_T_SR3 = new HashSet<TB_T_SR>();
            this.TB_T_SR4 = new HashSet<TB_T_SR>();
            this.TB_T_SR5 = new HashSet<TB_T_SR>();
        }
    
        public int BRANCH_ID { get; set; }
        public Nullable<int> CHANNEL_ID { get; set; }
        public string BRANCH_CODE { get; set; }
        public string BRANCH_NAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> UPPER_BRANCH_ID { get; set; }
        public Nullable<short> START_TIME_HOUR { get; set; }
        public Nullable<short> START_TIME_MINUTE { get; set; }
        public Nullable<short> END_TIME_HOUR { get; set; }
        public Nullable<short> END_TIME_MINUTE { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string BRANCH_HOME_NO { get; set; }
        public string BRANCH_MOO { get; set; }
        public string BRANCH_BUILDING { get; set; }
        public string BRANCH_FLOOR { get; set; }
        public string BRANCH_SOI { get; set; }
        public string BRANCH_STREET { get; set; }
        public string BRANCH_PROVINCE { get; set; }
        public string BRANCH_AMPHUR { get; set; }
        public string BRANCH_TAMBOL { get; set; }
        public string BRANCH_ZIPCODE { get; set; }
    
        public virtual ICollection<TB_M_POOL_BRANCH> TB_M_POOL_BRANCH { get; set; }
        public virtual ICollection<TB_T_SR_ACTIVITY> TB_T_SR_ACTIVITY { get; set; }
        public virtual ICollection<TB_T_NEWS_BRANCH> TB_T_NEWS_BRANCH { get; set; }
        public virtual ICollection<TB_R_BRANCH> TB_R_BRANCH1 { get; set; }
        public virtual TB_R_BRANCH TB_R_BRANCH2 { get; set; }
        public virtual ICollection<TB_R_BRANCH_CALENDAR> TB_R_BRANCH_CALENDAR { get; set; }
        public virtual ICollection<TB_T_SR_ACTIVITY> TB_T_SR_ACTIVITY1 { get; set; }
        public virtual ICollection<TB_T_SR_ACTIVITY> TB_T_SR_ACTIVITY2 { get; set; }
        public virtual TB_R_CHANNEL TB_R_CHANNEL { get; set; }
        public virtual ICollection<TB_R_USER> TB_R_USER { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR1 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR2 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR3 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR4 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR5 { get; set; }
    }
}
