//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_USER_PHONE
    {
        public int PHONE_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string PHONE_NO { get; set; }
        public Nullable<short> ORDER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual TB_R_USER TB_R_USER { get; set; }
    }
}
