//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_BRANCH_CALENDAR
    {
        public int BRANCH_CALENDAR_ID { get; set; }
        public int BRANCH_ID { get; set; }
        public System.DateTime HOLIDAY_DATE { get; set; }
        public string HOLIDAY_DESC { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual TB_R_BRANCH TB_R_BRANCH { get; set; }
    }
}
