//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_R_USER
    {
        public TB_R_USER()
        {
            this.TB_I_PROPERTY = new HashSet<TB_I_PROPERTY>();
            this.TB_I_SALE_ZONE = new HashSet<TB_I_SALE_ZONE>();
            this.TB_L_AUDIT_LOG = new HashSet<TB_L_AUDIT_LOG>();
            this.TB_L_SR_LOGGING = new HashSet<TB_L_SR_LOGGING>();
            this.TB_L_SR_LOGGING1 = new HashSet<TB_L_SR_LOGGING>();
            this.TB_L_SR_LOGGING2 = new HashSet<TB_L_SR_LOGGING>();
            this.TB_L_SR_LOGGING3 = new HashSet<TB_L_SR_LOGGING>();
            this.TB_M_AREA = new HashSet<TB_M_AREA>();
            this.TB_M_AREA1 = new HashSet<TB_M_AREA>();
            this.TB_M_AREA_SUBAREA = new HashSet<TB_M_AREA_SUBAREA>();
            this.TB_M_CONFIG_ROLE = new HashSet<TB_M_CONFIG_ROLE>();
            this.TB_M_CONFIG_ROLE1 = new HashSet<TB_M_CONFIG_ROLE>();
            this.TB_M_CONFIG_URL = new HashSet<TB_M_CONFIG_URL>();
            this.TB_M_CONFIG_URL1 = new HashSet<TB_M_CONFIG_URL>();
            this.TB_M_CONTACT = new HashSet<TB_M_CONTACT>();
            this.TB_M_CONTACT1 = new HashSet<TB_M_CONTACT>();
            this.TB_M_CONTACT_PHONE = new HashSet<TB_M_CONTACT_PHONE>();
            this.TB_M_CONTACT_PHONE1 = new HashSet<TB_M_CONTACT_PHONE>();
            this.TB_M_CUSTOMER = new HashSet<TB_M_CUSTOMER>();
            this.TB_M_CUSTOMER1 = new HashSet<TB_M_CUSTOMER>();
            this.TB_M_CUSTOMER2 = new HashSet<TB_M_CUSTOMER>();
            this.TB_M_CUSTOMER_ATTACHMENT = new HashSet<TB_M_CUSTOMER_ATTACHMENT>();
            this.TB_M_CUSTOMER_ATTACHMENT1 = new HashSet<TB_M_CUSTOMER_ATTACHMENT>();
            this.TB_M_CUSTOMER_CONTACT = new HashSet<TB_M_CUSTOMER_CONTACT>();
            this.TB_M_CUSTOMER_CONTACT1 = new HashSet<TB_M_CUSTOMER_CONTACT>();
            this.TB_M_MAP_PRODUCT = new HashSet<TB_M_MAP_PRODUCT>();
            this.TB_M_MAP_PRODUCT1 = new HashSet<TB_M_MAP_PRODUCT>();
            this.TB_M_MAP_PRODUCT2 = new HashSet<TB_M_MAP_PRODUCT>();
            this.TB_M_MAP_PRODUCT_QUESTIONGROUP = new HashSet<TB_M_MAP_PRODUCT_QUESTIONGROUP>();
            this.TB_M_MAP_PRODUCT_QUESTIONGROUP1 = new HashSet<TB_M_MAP_PRODUCT_QUESTIONGROUP>();
            this.TB_M_NOTE = new HashSet<TB_M_NOTE>();
            this.TB_M_NOTE1 = new HashSet<TB_M_NOTE>();
            this.TB_M_PHONE = new HashSet<TB_M_PHONE>();
            this.TB_M_PHONE1 = new HashSet<TB_M_PHONE>();
            this.TB_M_QUESTION = new HashSet<TB_M_QUESTION>();
            this.TB_M_QUESTION1 = new HashSet<TB_M_QUESTION>();
            this.TB_M_QUESTIONGROUP = new HashSet<TB_M_QUESTIONGROUP>();
            this.TB_M_QUESTIONGROUP1 = new HashSet<TB_M_QUESTIONGROUP>();
            this.TB_M_QUESTIONGROUP_QUESTION = new HashSet<TB_M_QUESTIONGROUP_QUESTION>();
            this.TB_M_QUESTIONGROUP_QUESTION1 = new HashSet<TB_M_QUESTIONGROUP_QUESTION>();
            this.TB_M_RELATIONSHIP = new HashSet<TB_M_RELATIONSHIP>();
            this.TB_M_RELATIONSHIP1 = new HashSet<TB_M_RELATIONSHIP>();
            this.TB_M_SLA = new HashSet<TB_M_SLA>();
            this.TB_M_SLA1 = new HashSet<TB_M_SLA>();
            this.TB_M_SUBAREA = new HashSet<TB_M_SUBAREA>();
            this.TB_M_SUBAREA1 = new HashSet<TB_M_SUBAREA>();
            this.TB_M_TYPE = new HashSet<TB_M_TYPE>();
            this.TB_M_TYPE1 = new HashSet<TB_M_TYPE>();
            this.TB_T_ATTACHMENT_TYPE = new HashSet<TB_T_ATTACHMENT_TYPE>();
            this.TB_R_USER1 = new HashSet<TB_R_USER>();
            this.TB_R_USER_PHONE = new HashSet<TB_R_USER_PHONE>();
            this.TB_T_SR_ACTIVITY = new HashSet<TB_T_SR_ACTIVITY>();
            this.TB_T_SR_ACTIVITY1 = new HashSet<TB_T_SR_ACTIVITY>();
            this.TB_T_SR_ATTACHMENT = new HashSet<TB_T_SR_ATTACHMENT>();
            this.TB_T_SR_ATTACHMENT1 = new HashSet<TB_T_SR_ATTACHMENT>();
            this.TB_T_DEFAULT_SEARCH = new HashSet<TB_T_DEFAULT_SEARCH>();
            this.TB_T_CALL_INFO = new HashSet<TB_T_CALL_INFO>();
            this.TB_T_READ_NEWS = new HashSet<TB_T_READ_NEWS>();
            this.TB_T_SR_ATTACHMENT_DOCUMENT_TYPE = new HashSet<TB_T_SR_ATTACHMENT_DOCUMENT_TYPE>();
            this.TB_C_SR_STATUS_CHANGE = new HashSet<TB_C_SR_STATUS_CHANGE>();
            this.TB_C_SR_STATUS_CHANGE1 = new HashSet<TB_C_SR_STATUS_CHANGE>();
            this.TB_M_POOL = new HashSet<TB_M_POOL>();
            this.TB_M_POOL1 = new HashSet<TB_M_POOL>();
            this.TB_T_NEWS = new HashSet<TB_T_NEWS>();
            this.TB_T_NEWS1 = new HashSet<TB_T_NEWS>();
            this.TB_T_JOB = new HashSet<TB_T_JOB>();
            this.TB_T_SR = new HashSet<TB_T_SR>();
            this.TB_T_SR1 = new HashSet<TB_T_SR>();
            this.TB_T_SR2 = new HashSet<TB_T_SR>();
            this.TB_T_SR3 = new HashSet<TB_T_SR>();
            this.TB_T_SR4 = new HashSet<TB_T_SR>();
            this.TB_T_SR5 = new HashSet<TB_T_SR>();
            this.TB_T_SR6 = new HashSet<TB_T_SR>();
        }
    
        public int USER_ID { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USERNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_GROUP { get; set; }
        public string POSITION_CODE { get; set; }
        public string MARKETING_CODE { get; set; }
        public string EMAIL { get; set; }
        public string ROLE_SALE { get; set; }
        public string MARKETING_TEAM { get; set; }
        public string LINE { get; set; }
        public string RANK { get; set; }
        public string EMPLOYEE_TYPE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string TELESALE_TEAM { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<bool> MARKETING_FLAG { get; set; }
        public Nullable<System.DateTime> EXPORT_DATE { get; set; }
    
        public virtual ICollection<TB_I_PROPERTY> TB_I_PROPERTY { get; set; }
        public virtual ICollection<TB_I_SALE_ZONE> TB_I_SALE_ZONE { get; set; }
        public virtual ICollection<TB_L_AUDIT_LOG> TB_L_AUDIT_LOG { get; set; }
        public virtual ICollection<TB_L_SR_LOGGING> TB_L_SR_LOGGING { get; set; }
        public virtual ICollection<TB_L_SR_LOGGING> TB_L_SR_LOGGING1 { get; set; }
        public virtual ICollection<TB_L_SR_LOGGING> TB_L_SR_LOGGING2 { get; set; }
        public virtual ICollection<TB_L_SR_LOGGING> TB_L_SR_LOGGING3 { get; set; }
        public virtual ICollection<TB_M_AREA> TB_M_AREA { get; set; }
        public virtual ICollection<TB_M_AREA> TB_M_AREA1 { get; set; }
        public virtual ICollection<TB_M_AREA_SUBAREA> TB_M_AREA_SUBAREA { get; set; }
        public virtual ICollection<TB_M_CONFIG_ROLE> TB_M_CONFIG_ROLE { get; set; }
        public virtual ICollection<TB_M_CONFIG_ROLE> TB_M_CONFIG_ROLE1 { get; set; }
        public virtual ICollection<TB_M_CONFIG_URL> TB_M_CONFIG_URL { get; set; }
        public virtual ICollection<TB_M_CONFIG_URL> TB_M_CONFIG_URL1 { get; set; }
        public virtual ICollection<TB_M_CONTACT> TB_M_CONTACT { get; set; }
        public virtual ICollection<TB_M_CONTACT> TB_M_CONTACT1 { get; set; }
        public virtual ICollection<TB_M_CONTACT_PHONE> TB_M_CONTACT_PHONE { get; set; }
        public virtual ICollection<TB_M_CONTACT_PHONE> TB_M_CONTACT_PHONE1 { get; set; }
        public virtual ICollection<TB_M_CUSTOMER> TB_M_CUSTOMER { get; set; }
        public virtual ICollection<TB_M_CUSTOMER> TB_M_CUSTOMER1 { get; set; }
        public virtual ICollection<TB_M_CUSTOMER> TB_M_CUSTOMER2 { get; set; }
        public virtual ICollection<TB_M_CUSTOMER_ATTACHMENT> TB_M_CUSTOMER_ATTACHMENT { get; set; }
        public virtual ICollection<TB_M_CUSTOMER_ATTACHMENT> TB_M_CUSTOMER_ATTACHMENT1 { get; set; }
        public virtual ICollection<TB_M_CUSTOMER_CONTACT> TB_M_CUSTOMER_CONTACT { get; set; }
        public virtual ICollection<TB_M_CUSTOMER_CONTACT> TB_M_CUSTOMER_CONTACT1 { get; set; }
        public virtual ICollection<TB_M_MAP_PRODUCT> TB_M_MAP_PRODUCT { get; set; }
        public virtual ICollection<TB_M_MAP_PRODUCT> TB_M_MAP_PRODUCT1 { get; set; }
        public virtual ICollection<TB_M_MAP_PRODUCT> TB_M_MAP_PRODUCT2 { get; set; }
        public virtual ICollection<TB_M_MAP_PRODUCT_QUESTIONGROUP> TB_M_MAP_PRODUCT_QUESTIONGROUP { get; set; }
        public virtual ICollection<TB_M_MAP_PRODUCT_QUESTIONGROUP> TB_M_MAP_PRODUCT_QUESTIONGROUP1 { get; set; }
        public virtual ICollection<TB_M_NOTE> TB_M_NOTE { get; set; }
        public virtual ICollection<TB_M_NOTE> TB_M_NOTE1 { get; set; }
        public virtual ICollection<TB_M_PHONE> TB_M_PHONE { get; set; }
        public virtual ICollection<TB_M_PHONE> TB_M_PHONE1 { get; set; }
        public virtual ICollection<TB_M_QUESTION> TB_M_QUESTION { get; set; }
        public virtual ICollection<TB_M_QUESTION> TB_M_QUESTION1 { get; set; }
        public virtual ICollection<TB_M_QUESTIONGROUP> TB_M_QUESTIONGROUP { get; set; }
        public virtual ICollection<TB_M_QUESTIONGROUP> TB_M_QUESTIONGROUP1 { get; set; }
        public virtual ICollection<TB_M_QUESTIONGROUP_QUESTION> TB_M_QUESTIONGROUP_QUESTION { get; set; }
        public virtual ICollection<TB_M_QUESTIONGROUP_QUESTION> TB_M_QUESTIONGROUP_QUESTION1 { get; set; }
        public virtual ICollection<TB_M_RELATIONSHIP> TB_M_RELATIONSHIP { get; set; }
        public virtual ICollection<TB_M_RELATIONSHIP> TB_M_RELATIONSHIP1 { get; set; }
        public virtual ICollection<TB_M_SLA> TB_M_SLA { get; set; }
        public virtual ICollection<TB_M_SLA> TB_M_SLA1 { get; set; }
        public virtual ICollection<TB_M_SUBAREA> TB_M_SUBAREA { get; set; }
        public virtual ICollection<TB_M_SUBAREA> TB_M_SUBAREA1 { get; set; }
        public virtual ICollection<TB_M_TYPE> TB_M_TYPE { get; set; }
        public virtual ICollection<TB_M_TYPE> TB_M_TYPE1 { get; set; }
        public virtual TB_R_BRANCH TB_R_BRANCH { get; set; }
        public virtual ICollection<TB_T_ATTACHMENT_TYPE> TB_T_ATTACHMENT_TYPE { get; set; }
        public virtual ICollection<TB_R_USER> TB_R_USER1 { get; set; }
        public virtual TB_R_USER TB_R_USER2 { get; set; }
        public virtual ICollection<TB_R_USER_PHONE> TB_R_USER_PHONE { get; set; }
        public virtual ICollection<TB_T_SR_ACTIVITY> TB_T_SR_ACTIVITY { get; set; }
        public virtual ICollection<TB_T_SR_ACTIVITY> TB_T_SR_ACTIVITY1 { get; set; }
        public virtual ICollection<TB_T_SR_ATTACHMENT> TB_T_SR_ATTACHMENT { get; set; }
        public virtual ICollection<TB_T_SR_ATTACHMENT> TB_T_SR_ATTACHMENT1 { get; set; }
        public virtual ICollection<TB_T_DEFAULT_SEARCH> TB_T_DEFAULT_SEARCH { get; set; }
        public virtual ICollection<TB_T_CALL_INFO> TB_T_CALL_INFO { get; set; }
        public virtual ICollection<TB_T_READ_NEWS> TB_T_READ_NEWS { get; set; }
        public virtual ICollection<TB_T_SR_ATTACHMENT_DOCUMENT_TYPE> TB_T_SR_ATTACHMENT_DOCUMENT_TYPE { get; set; }
        public virtual ICollection<TB_C_SR_STATUS_CHANGE> TB_C_SR_STATUS_CHANGE { get; set; }
        public virtual ICollection<TB_C_SR_STATUS_CHANGE> TB_C_SR_STATUS_CHANGE1 { get; set; }
        public virtual ICollection<TB_M_POOL> TB_M_POOL { get; set; }
        public virtual ICollection<TB_M_POOL> TB_M_POOL1 { get; set; }
        public virtual ICollection<TB_T_NEWS> TB_T_NEWS { get; set; }
        public virtual ICollection<TB_T_NEWS> TB_T_NEWS1 { get; set; }
        public virtual ICollection<TB_T_JOB> TB_T_JOB { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR1 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR2 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR3 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR4 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR5 { get; set; }
        public virtual ICollection<TB_T_SR> TB_T_SR6 { get; set; }
    }
}
