//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_DNC_TRANSACTION_HIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_DNC_TRANSACTION_HIS()
        {
            this.TB_T_DNC_TRANSACTION_HIS_EMAIL = new HashSet<TB_T_DNC_TRANSACTION_HIS_EMAIL>();
            this.TB_T_DNC_TRANSACTION_HIS_PHONE = new HashSet<TB_T_DNC_TRANSACTION_HIS_PHONE>();
            this.TB_T_DNC_TRANSACTION_HIS_PRODUCT = new HashSet<TB_T_DNC_TRANSACTION_HIS_PRODUCT>();
        }
    
        public int DNC_TRANSACTION_HIS_ID { get; set; }
        public int DNC_TRANSACTION_ID { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
        public string CARD_NO { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public string FROM_SYSTEM { get; set; }
        public Nullable<decimal> KKCIS_ID { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string TRANS_TYPE { get; set; }
        public string SALES_BLOCK_TELEPHONE { get; set; }
        public string SALES_BLOCK_SMS { get; set; }
        public string SALES_BLOCK_EMAIL { get; set; }
        public string SALES_BLOCK_ALL_PRODUCT { get; set; }
        public string INFORMATION_BLOCK_TELEPHONE { get; set; }
        public string INFORMATION_BLOCK_SMS { get; set; }
        public string INFORMATION_BLOCK_EMAIL { get; set; }
        public string INFORMATION_BLOCK_ALL_PRODUCT { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERNAME { get; set; }
    
        public virtual TB_T_DNC_TRANSACTION TB_T_DNC_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_TRANSACTION_HIS_EMAIL> TB_T_DNC_TRANSACTION_HIS_EMAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_TRANSACTION_HIS_PHONE> TB_T_DNC_TRANSACTION_HIS_PHONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_TRANSACTION_HIS_PRODUCT> TB_T_DNC_TRANSACTION_HIS_PRODUCT { get; set; }
    }
}
