//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_DNC_TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_DNC_TRANSACTION()
        {
            this.TB_T_DNC_ACTIVITY_TYPE = new HashSet<TB_T_DNC_ACTIVITY_TYPE>();
            this.TB_T_DNC_EMAIL = new HashSet<TB_T_DNC_EMAIL>();
            this.TB_T_DNC_PHONE_NO = new HashSet<TB_T_DNC_PHONE_NO>();
            this.TB_T_DNC_TRANSACTION_HIS = new HashSet<TB_T_DNC_TRANSACTION_HIS>();
        }
    
        public int DNC_TRANSACTION_ID { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
        public string CARD_NO { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public string FROM_SYSTEM { get; set; }
        public Nullable<decimal> KKCIS_ID { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string TRANS_TYPE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_ACTIVITY_TYPE> TB_T_DNC_ACTIVITY_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_EMAIL> TB_T_DNC_EMAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_PHONE_NO> TB_T_DNC_PHONE_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_TRANSACTION_HIS> TB_T_DNC_TRANSACTION_HIS { get; set; }
    }
}
