//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_ATTACHMENT_DOCUMENT_TYPE
    {
        public int SR_ATTACHMENT_DOCUMENT_TYPE_ID { get; set; }
        public int SR_ATTACHMENT_ID { get; set; }
        public int DOCUMENT_TYPE_ID { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USERNAME { get; set; }
    
        public virtual TB_M_DOCUMENT_TYPE TB_M_DOCUMENT_TYPE { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_T_SR_ATTACHMENT TB_T_SR_ATTACHMENT { get; set; }
    }
}
