//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_DNC_LOAD_LIST_DATA
    {
        public int DNC_LOAD_LIST_DATA_ID { get; set; }
        public int DNC_LOAD_LIST_ID { get; set; }
        public int ROW_NO { get; set; }
        public Nullable<int> SUBSCRIPT_TYPE_ID { get; set; }
        public string CARD_NO { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public Nullable<decimal> KKCIS_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string EMAIL { get; set; }
        public string SALES_BLOCK_TELEPHONE { get; set; }
        public string SALES_BLOCK_SMS { get; set; }
        public string SALES_BLOCK_EMAIL { get; set; }
        public string SALES_BLOCK_ALL_PRODUCT { get; set; }
        public string INFORMATION_BLOCK_TELEPHONE { get; set; }
        public string INFORMATION_BLOCK_SMS { get; set; }
        public string INFORMATION_BLOCK_EMAIL { get; set; }
        public string INFORMATION_BLOCK_ALL_PRODUCT { get; set; }
        public string STATUS { get; set; }
        public string TRANS_TYPE { get; set; }
        public Nullable<int> DNC_TRANSACTION_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
    
        public virtual TB_T_DNC_LOAD_LIST TB_T_DNC_LOAD_LIST { get; set; }
    }
}
