//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_ATTACHMENT
    {
        public TB_T_SR_ATTACHMENT()
        {
            this.TB_T_ATTACHMENT_TYPE = new HashSet<TB_T_ATTACHMENT_TYPE>();
            this.TB_T_SR_ATTACHMENT_DOCUMENT_TYPE = new HashSet<TB_T_SR_ATTACHMENT_DOCUMENT_TYPE>();
        }
    
        public int SR_ATTACHMENT_ID { get; set; }
        public Nullable<int> SR_ID { get; set; }
        public Nullable<int> SR_ACTIVITY_ID { get; set; }
        public string SR_ATTACHMENT_FILE_NAME { get; set; }
        public string SR_ATTACHMENT_CONTENT_TYPE { get; set; }
        public string SR_ATTACHMENT_URL { get; set; }
        public string SR_ATTACHMENT_NAME { get; set; }
        public string SR_ATTACHMENT_DESC { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
    
        public virtual TB_M_CUSTOMER TB_M_CUSTOMER { get; set; }
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
        public virtual ICollection<TB_T_ATTACHMENT_TYPE> TB_T_ATTACHMENT_TYPE { get; set; }
        public virtual TB_T_SR_ACTIVITY TB_T_SR_ACTIVITY { get; set; }
        public virtual ICollection<TB_T_SR_ATTACHMENT_DOCUMENT_TYPE> TB_T_SR_ATTACHMENT_DOCUMENT_TYPE { get; set; }
        public virtual TB_T_SR TB_T_SR { get; set; }
    }
}
