//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_PREPARE_EMAIL
    {
        public int SR_PREPARE_EMAIL_ID { get; set; }
        public int SR_ACTIVITY_ID { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string EMAIL_CONTENT { get; set; }
        public string EMAIL_SENDER { get; set; }
        public string EMAIL_SUBJECT { get; set; }
        public Nullable<int> RULE_ACTIVITY_ID { get; set; }
        public string EXPORT_STATUS { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public bool IS_DELETE { get; set; }
        public string EMAIL_CREATE_BY { get; set; }
        public Nullable<int> THIS_ALERT { get; set; }
        public Nullable<int> WORKING_MINUTE { get; set; }
        public Nullable<System.DateTime> RULE_NEXT_SLA { get; set; }
        public Nullable<System.DateTime> RULE_CURRENT_SLA { get; set; }
    
        public virtual TB_T_SR_ACTIVITY TB_T_SR_ACTIVITY { get; set; }
    }
}
