//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_DNC_ACTIVITY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_DNC_ACTIVITY_TYPE()
        {
            this.TB_T_DNC_ACTIVITY_PRODUCT = new HashSet<TB_T_DNC_ACTIVITY_PRODUCT>();
        }
    
        public int DNC_ACTIVITY_TYPE_ID { get; set; }
        public Nullable<int> DNC_TRANSACTION_ID { get; set; }
        public string SALES_BLOCK_TELEPHONE { get; set; }
        public string SALES_BLOCK_SMS { get; set; }
        public string SALES_BLOCK_EMAIL { get; set; }
        public string SALES_BLOCK_ALL_PRODUCT { get; set; }
        public string INFORMATION_BLOCK_TELEPHONE { get; set; }
        public string INFORMATION_BLOCK_SMS { get; set; }
        public string INFORMATION_BLOCK_EMAIL { get; set; }
        public string INFORMATION_BLOCK_ALL_PRODUCT { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATE_USERNAME { get; set; }
        public string UPDATE_USERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DNC_ACTIVITY_PRODUCT> TB_T_DNC_ACTIVITY_PRODUCT { get; set; }
        public virtual TB_T_DNC_TRANSACTION TB_T_DNC_TRANSACTION { get; set; }
    }
}
