//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_NEWS_BRANCH
    {
        public int NEWS_BRANCH_ID { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
    
        public virtual TB_R_BRANCH TB_R_BRANCH { get; set; }
        public virtual TB_T_NEWS TB_T_NEWS { get; set; }
    }
}
