//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_CALL_INFO
    {
        public int CALL_INFO_ID { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public string CALL_ID { get; set; }
        public string A_NO { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CALL_TYPE { get; set; }
        public string IVR_LANG { get; set; }
    
        public virtual TB_R_USER TB_R_USER { get; set; }
    }
}
