//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SEND_OTP
    {
        public int SEND_OTP_ID { get; set; }
        public string CSM_REFNO { get; set; }
        public string CALL_ID { get; set; }
        public string TXN_ID { get; set; }
        public string ID_CARD { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string IDENTIFICATION_TYPE { get; set; }
        public string USER_ACTION { get; set; }
        public string CLIENT_IP { get; set; }
        public string METHOD { get; set; }
        public string TEMPLATE_ID { get; set; }
        public string PRODUCT_DESC { get; set; }
        public string RESERVE_FIELD1 { get; set; }
        public string REQUEST_IVR_REFNO { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public string REQUEST_STATUS_CODE { get; set; }
        public string REQUEST_ERROR_CODE { get; set; }
        public string REQUEST_ERROR_DESC { get; set; }
        public string REQUEST_CAA_ERROR_CODE { get; set; }
        public string REQUEST_CAA_ERROR_DESC { get; set; }
        public string REQUEST_OTP_PREFIX { get; set; }
        public string REQUEST_OTP_DETAIL { get; set; }
        public string REQUEST_OTP_SUFFIX { get; set; }
        public string RESULT_IVR_REFNO { get; set; }
        public Nullable<System.DateTime> RESULT_DATE { get; set; }
        public string RESULT_STATUS_CODE { get; set; }
        public string RESULT_ERROR_CODE { get; set; }
        public string RESULT_ERROR_DESC { get; set; }
        public string RESULT_CAA_ERROR_CODE { get; set; }
        public string RESULT_CAA_ERROR_DESC { get; set; }
        public string RESULT_OTP_PREFIX { get; set; }
        public string RESULT_OTP_DETAIL { get; set; }
        public string RESULT_OTP_SUFFIX { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
