//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_DNC_EXPORT_FLAG
    {
        public int DNC_EXPORT_FLAG_ID { get; set; }
        public string PHONE_NO { get; set; }
        public string STATUS_TO_OTHER { get; set; }
        public string STATUS_TO_TOT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
