//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_REPLY_EMAIL
    {
        public int SR_REPLY_EMAIL_ID { get; set; }
        public Nullable<int> SR_ID { get; set; }
        public Nullable<int> SR_STATUS_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<bool> IS_PROCESS { get; set; }
        public Nullable<System.DateTime> PROCESS_DATE { get; set; }
        public string ERROR_CODE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public Nullable<int> JOB_ID { get; set; }
    
        public virtual TB_C_SR_STATUS TB_C_SR_STATUS { get; set; }
        public virtual TB_T_JOB TB_T_JOB { get; set; }
        public virtual TB_T_SR TB_T_SR { get; set; }
    }
}
