//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Web.CSMMailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kiatnakinbank.com/services/CSM/CSMMailService", ConfigurationName="CSMMailService.ICSMMailService")]
    public interface ICSMMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "ox", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "oxResponse")]
        CSM.Service.Messages.SchedTask.JobTaskResponse GetMailbox(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "ox", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMMailService/ICSMMailService/GetMailb" +
            "oxResponse")]
        System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.JobTaskResponse> GetMailboxAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSMMailServiceChannel : CSM.Web.CSMMailService.ICSMMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSMMailServiceClient : System.ServiceModel.ClientBase<CSM.Web.CSMMailService.ICSMMailService>, CSM.Web.CSMMailService.ICSMMailService {
        
        public CSMMailServiceClient() {
        }
        
        public CSMMailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSMMailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMMailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMMailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSM.Service.Messages.SchedTask.JobTaskResponse GetMailbox(string username, string password) {
            return base.Channel.GetMailbox(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.Messages.SchedTask.JobTaskResponse> GetMailboxAsync(string username, string password) {
            return base.Channel.GetMailboxAsync(username, password);
        }
    }
}
