//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.ScheduledTask.CSMFileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportAFSTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.StatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse))]
    public partial class ImportAFSTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] FileListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrPropField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrSaleZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPropField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSaleZonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] FileList {
            get {
                return this.FileListField;
            }
            set {
                if ((object.ReferenceEquals(this.FileListField, value) != true)) {
                    this.FileListField = value;
                    this.RaisePropertyChanged("FileList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfComplete {
            get {
                return this.NumOfCompleteField;
            }
            set {
                if ((this.NumOfCompleteField.Equals(value) != true)) {
                    this.NumOfCompleteField = value;
                    this.RaisePropertyChanged("NumOfComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrProp {
            get {
                return this.NumOfErrPropField;
            }
            set {
                if ((this.NumOfErrPropField.Equals(value) != true)) {
                    this.NumOfErrPropField = value;
                    this.RaisePropertyChanged("NumOfErrProp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrSaleZone {
            get {
                return this.NumOfErrSaleZoneField;
            }
            set {
                if ((this.NumOfErrSaleZoneField.Equals(value) != true)) {
                    this.NumOfErrSaleZoneField = value;
                    this.RaisePropertyChanged("NumOfErrSaleZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfProp {
            get {
                return this.NumOfPropField;
            }
            set {
                if ((this.NumOfPropField.Equals(value) != true)) {
                    this.NumOfPropField = value;
                    this.RaisePropertyChanged("NumOfProp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSaleZones {
            get {
                return this.NumOfSaleZonesField;
            }
            set {
                if ((this.NumOfSaleZonesField.Equals(value) != true)) {
                    this.NumOfSaleZonesField = value;
                    this.RaisePropertyChanged("NumOfSaleZones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Common")]
    [System.SerializableAttribute()]
    public partial class StatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BranchCodeNotFoundListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BranchCodeNotFoundList {
            get {
                return this.BranchCodeNotFoundListField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeNotFoundListField, value) != true)) {
                    this.BranchCodeNotFoundListField = value;
                    this.RaisePropertyChanged("BranchCodeNotFoundList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportAFSTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    public partial class ExportAFSTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfActivity {
            get {
                return this.NumOfActivityField;
            }
            set {
                if ((this.NumOfActivityField.Equals(value) != true)) {
                    this.NumOfActivityField = value;
                    this.RaisePropertyChanged("NumOfActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportNCBTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    public partial class ExportNCBTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfNew {
            get {
                return this.NumOfNewField;
            }
            set {
                if ((this.NumOfNewField.Equals(value) != true)) {
                    this.NumOfNewField = value;
                    this.RaisePropertyChanged("NumOfNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfUpdate {
            get {
                return this.NumOfUpdateField;
            }
            set {
                if ((this.NumOfUpdateField.Equals(value) != true)) {
                    this.NumOfUpdateField = value;
                    this.RaisePropertyChanged("NumOfUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportBDWTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.StatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse))]
    public partial class ImportBDWTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] FileListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfBdwContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] FileList {
            get {
                return this.FileListField;
            }
            set {
                if ((object.ReferenceEquals(this.FileListField, value) != true)) {
                    this.FileListField = value;
                    this.RaisePropertyChanged("FileList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfBdwContact {
            get {
                return this.NumOfBdwContactField;
            }
            set {
                if ((this.NumOfBdwContactField.Equals(value) != true)) {
                    this.NumOfBdwContactField = value;
                    this.RaisePropertyChanged("NumOfBdwContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfComplete {
            get {
                return this.NumOfCompleteField;
            }
            set {
                if ((this.NumOfCompleteField.Equals(value) != true)) {
                    this.NumOfCompleteField = value;
                    this.RaisePropertyChanged("NumOfComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfError {
            get {
                return this.NumOfErrorField;
            }
            set {
                if ((this.NumOfErrorField.Equals(value) != true)) {
                    this.NumOfErrorField = value;
                    this.RaisePropertyChanged("NumOfError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportCISTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.StatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse))]
    public partial class ImportCISTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] FileErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] FileListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfAddressCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfAddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfAddressTypeCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfAddressTypeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCorCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCountryCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCountryErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCusEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCusEmailCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCusEmailErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCusPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCusPhoneCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCusPhoneErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfDisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfDistrictCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfDistrictErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfEmailCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfEmailtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfEmailtypeCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfEmailtypeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrCorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrIndivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrSubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfIndivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfIndivCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPhoneCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPhonetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPhonetypeCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPhonetypeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfProdCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfProdErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfProvinceCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfProvinceErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubAddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubDisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubDistrictCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubDistrictErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubTypeCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfSubTypeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfTitleCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfTitleErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numOfErrAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] FileErrorList {
            get {
                return this.FileErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.FileErrorListField, value) != true)) {
                    this.FileErrorListField = value;
                    this.RaisePropertyChanged("FileErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] FileList {
            get {
                return this.FileListField;
            }
            set {
                if ((object.ReferenceEquals(this.FileListField, value) != true)) {
                    this.FileListField = value;
                    this.RaisePropertyChanged("FileList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfAddressComplete {
            get {
                return this.NumOfAddressCompleteField;
            }
            set {
                if ((this.NumOfAddressCompleteField.Equals(value) != true)) {
                    this.NumOfAddressCompleteField = value;
                    this.RaisePropertyChanged("NumOfAddressComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfAddressType {
            get {
                return this.NumOfAddressTypeField;
            }
            set {
                if ((this.NumOfAddressTypeField.Equals(value) != true)) {
                    this.NumOfAddressTypeField = value;
                    this.RaisePropertyChanged("NumOfAddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfAddressTypeComplete {
            get {
                return this.NumOfAddressTypeCompleteField;
            }
            set {
                if ((this.NumOfAddressTypeCompleteField.Equals(value) != true)) {
                    this.NumOfAddressTypeCompleteField = value;
                    this.RaisePropertyChanged("NumOfAddressTypeComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfAddressTypeError {
            get {
                return this.NumOfAddressTypeErrorField;
            }
            set {
                if ((this.NumOfAddressTypeErrorField.Equals(value) != true)) {
                    this.NumOfAddressTypeErrorField = value;
                    this.RaisePropertyChanged("NumOfAddressTypeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCor {
            get {
                return this.NumOfCorField;
            }
            set {
                if ((this.NumOfCorField.Equals(value) != true)) {
                    this.NumOfCorField = value;
                    this.RaisePropertyChanged("NumOfCor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCorComplete {
            get {
                return this.NumOfCorCompleteField;
            }
            set {
                if ((this.NumOfCorCompleteField.Equals(value) != true)) {
                    this.NumOfCorCompleteField = value;
                    this.RaisePropertyChanged("NumOfCorComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCountry {
            get {
                return this.NumOfCountryField;
            }
            set {
                if ((this.NumOfCountryField.Equals(value) != true)) {
                    this.NumOfCountryField = value;
                    this.RaisePropertyChanged("NumOfCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCountryComplete {
            get {
                return this.NumOfCountryCompleteField;
            }
            set {
                if ((this.NumOfCountryCompleteField.Equals(value) != true)) {
                    this.NumOfCountryCompleteField = value;
                    this.RaisePropertyChanged("NumOfCountryComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCountryError {
            get {
                return this.NumOfCountryErrorField;
            }
            set {
                if ((this.NumOfCountryErrorField.Equals(value) != true)) {
                    this.NumOfCountryErrorField = value;
                    this.RaisePropertyChanged("NumOfCountryError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCusEmail {
            get {
                return this.NumOfCusEmailField;
            }
            set {
                if ((this.NumOfCusEmailField.Equals(value) != true)) {
                    this.NumOfCusEmailField = value;
                    this.RaisePropertyChanged("NumOfCusEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCusEmailComplete {
            get {
                return this.NumOfCusEmailCompleteField;
            }
            set {
                if ((this.NumOfCusEmailCompleteField.Equals(value) != true)) {
                    this.NumOfCusEmailCompleteField = value;
                    this.RaisePropertyChanged("NumOfCusEmailComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCusEmailError {
            get {
                return this.NumOfCusEmailErrorField;
            }
            set {
                if ((this.NumOfCusEmailErrorField.Equals(value) != true)) {
                    this.NumOfCusEmailErrorField = value;
                    this.RaisePropertyChanged("NumOfCusEmailError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCusPhone {
            get {
                return this.NumOfCusPhoneField;
            }
            set {
                if ((this.NumOfCusPhoneField.Equals(value) != true)) {
                    this.NumOfCusPhoneField = value;
                    this.RaisePropertyChanged("NumOfCusPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCusPhoneComplete {
            get {
                return this.NumOfCusPhoneCompleteField;
            }
            set {
                if ((this.NumOfCusPhoneCompleteField.Equals(value) != true)) {
                    this.NumOfCusPhoneCompleteField = value;
                    this.RaisePropertyChanged("NumOfCusPhoneComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfCusPhoneError {
            get {
                return this.NumOfCusPhoneErrorField;
            }
            set {
                if ((this.NumOfCusPhoneErrorField.Equals(value) != true)) {
                    this.NumOfCusPhoneErrorField = value;
                    this.RaisePropertyChanged("NumOfCusPhoneError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfDis {
            get {
                return this.NumOfDisField;
            }
            set {
                if ((this.NumOfDisField.Equals(value) != true)) {
                    this.NumOfDisField = value;
                    this.RaisePropertyChanged("NumOfDis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfDistrictComplete {
            get {
                return this.NumOfDistrictCompleteField;
            }
            set {
                if ((this.NumOfDistrictCompleteField.Equals(value) != true)) {
                    this.NumOfDistrictCompleteField = value;
                    this.RaisePropertyChanged("NumOfDistrictComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfDistrictError {
            get {
                return this.NumOfDistrictErrorField;
            }
            set {
                if ((this.NumOfDistrictErrorField.Equals(value) != true)) {
                    this.NumOfDistrictErrorField = value;
                    this.RaisePropertyChanged("NumOfDistrictError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfEmailComplete {
            get {
                return this.NumOfEmailCompleteField;
            }
            set {
                if ((this.NumOfEmailCompleteField.Equals(value) != true)) {
                    this.NumOfEmailCompleteField = value;
                    this.RaisePropertyChanged("NumOfEmailComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfEmailtype {
            get {
                return this.NumOfEmailtypeField;
            }
            set {
                if ((this.NumOfEmailtypeField.Equals(value) != true)) {
                    this.NumOfEmailtypeField = value;
                    this.RaisePropertyChanged("NumOfEmailtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfEmailtypeComplete {
            get {
                return this.NumOfEmailtypeCompleteField;
            }
            set {
                if ((this.NumOfEmailtypeCompleteField.Equals(value) != true)) {
                    this.NumOfEmailtypeCompleteField = value;
                    this.RaisePropertyChanged("NumOfEmailtypeComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfEmailtypeError {
            get {
                return this.NumOfEmailtypeErrorField;
            }
            set {
                if ((this.NumOfEmailtypeErrorField.Equals(value) != true)) {
                    this.NumOfEmailtypeErrorField = value;
                    this.RaisePropertyChanged("NumOfEmailtypeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrCor {
            get {
                return this.NumOfErrCorField;
            }
            set {
                if ((this.NumOfErrCorField.Equals(value) != true)) {
                    this.NumOfErrCorField = value;
                    this.RaisePropertyChanged("NumOfErrCor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrEmail {
            get {
                return this.NumOfErrEmailField;
            }
            set {
                if ((this.NumOfErrEmailField.Equals(value) != true)) {
                    this.NumOfErrEmailField = value;
                    this.RaisePropertyChanged("NumOfErrEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrIndiv {
            get {
                return this.NumOfErrIndivField;
            }
            set {
                if ((this.NumOfErrIndivField.Equals(value) != true)) {
                    this.NumOfErrIndivField = value;
                    this.RaisePropertyChanged("NumOfErrIndiv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrPhone {
            get {
                return this.NumOfErrPhoneField;
            }
            set {
                if ((this.NumOfErrPhoneField.Equals(value) != true)) {
                    this.NumOfErrPhoneField = value;
                    this.RaisePropertyChanged("NumOfErrPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfErrSub {
            get {
                return this.NumOfErrSubField;
            }
            set {
                if ((this.NumOfErrSubField.Equals(value) != true)) {
                    this.NumOfErrSubField = value;
                    this.RaisePropertyChanged("NumOfErrSub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfIndiv {
            get {
                return this.NumOfIndivField;
            }
            set {
                if ((this.NumOfIndivField.Equals(value) != true)) {
                    this.NumOfIndivField = value;
                    this.RaisePropertyChanged("NumOfIndiv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfIndivComplete {
            get {
                return this.NumOfIndivCompleteField;
            }
            set {
                if ((this.NumOfIndivCompleteField.Equals(value) != true)) {
                    this.NumOfIndivCompleteField = value;
                    this.RaisePropertyChanged("NumOfIndivComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPhoneComplete {
            get {
                return this.NumOfPhoneCompleteField;
            }
            set {
                if ((this.NumOfPhoneCompleteField.Equals(value) != true)) {
                    this.NumOfPhoneCompleteField = value;
                    this.RaisePropertyChanged("NumOfPhoneComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPhonetype {
            get {
                return this.NumOfPhonetypeField;
            }
            set {
                if ((this.NumOfPhonetypeField.Equals(value) != true)) {
                    this.NumOfPhonetypeField = value;
                    this.RaisePropertyChanged("NumOfPhonetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPhonetypeComplete {
            get {
                return this.NumOfPhonetypeCompleteField;
            }
            set {
                if ((this.NumOfPhonetypeCompleteField.Equals(value) != true)) {
                    this.NumOfPhonetypeCompleteField = value;
                    this.RaisePropertyChanged("NumOfPhonetypeComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPhonetypeError {
            get {
                return this.NumOfPhonetypeErrorField;
            }
            set {
                if ((this.NumOfPhonetypeErrorField.Equals(value) != true)) {
                    this.NumOfPhonetypeErrorField = value;
                    this.RaisePropertyChanged("NumOfPhonetypeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPro {
            get {
                return this.NumOfProField;
            }
            set {
                if ((this.NumOfProField.Equals(value) != true)) {
                    this.NumOfProField = value;
                    this.RaisePropertyChanged("NumOfPro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfProd {
            get {
                return this.NumOfProdField;
            }
            set {
                if ((this.NumOfProdField.Equals(value) != true)) {
                    this.NumOfProdField = value;
                    this.RaisePropertyChanged("NumOfProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfProdComplete {
            get {
                return this.NumOfProdCompleteField;
            }
            set {
                if ((this.NumOfProdCompleteField.Equals(value) != true)) {
                    this.NumOfProdCompleteField = value;
                    this.RaisePropertyChanged("NumOfProdComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfProdError {
            get {
                return this.NumOfProdErrorField;
            }
            set {
                if ((this.NumOfProdErrorField.Equals(value) != true)) {
                    this.NumOfProdErrorField = value;
                    this.RaisePropertyChanged("NumOfProdError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfProvinceComplete {
            get {
                return this.NumOfProvinceCompleteField;
            }
            set {
                if ((this.NumOfProvinceCompleteField.Equals(value) != true)) {
                    this.NumOfProvinceCompleteField = value;
                    this.RaisePropertyChanged("NumOfProvinceComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfProvinceError {
            get {
                return this.NumOfProvinceErrorField;
            }
            set {
                if ((this.NumOfProvinceErrorField.Equals(value) != true)) {
                    this.NumOfProvinceErrorField = value;
                    this.RaisePropertyChanged("NumOfProvinceError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSub {
            get {
                return this.NumOfSubField;
            }
            set {
                if ((this.NumOfSubField.Equals(value) != true)) {
                    this.NumOfSubField = value;
                    this.RaisePropertyChanged("NumOfSub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubAdd {
            get {
                return this.NumOfSubAddField;
            }
            set {
                if ((this.NumOfSubAddField.Equals(value) != true)) {
                    this.NumOfSubAddField = value;
                    this.RaisePropertyChanged("NumOfSubAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubComplete {
            get {
                return this.NumOfSubCompleteField;
            }
            set {
                if ((this.NumOfSubCompleteField.Equals(value) != true)) {
                    this.NumOfSubCompleteField = value;
                    this.RaisePropertyChanged("NumOfSubComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubDis {
            get {
                return this.NumOfSubDisField;
            }
            set {
                if ((this.NumOfSubDisField.Equals(value) != true)) {
                    this.NumOfSubDisField = value;
                    this.RaisePropertyChanged("NumOfSubDis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubDistrictComplete {
            get {
                return this.NumOfSubDistrictCompleteField;
            }
            set {
                if ((this.NumOfSubDistrictCompleteField.Equals(value) != true)) {
                    this.NumOfSubDistrictCompleteField = value;
                    this.RaisePropertyChanged("NumOfSubDistrictComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubDistrictError {
            get {
                return this.NumOfSubDistrictErrorField;
            }
            set {
                if ((this.NumOfSubDistrictErrorField.Equals(value) != true)) {
                    this.NumOfSubDistrictErrorField = value;
                    this.RaisePropertyChanged("NumOfSubDistrictError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubMail {
            get {
                return this.NumOfSubMailField;
            }
            set {
                if ((this.NumOfSubMailField.Equals(value) != true)) {
                    this.NumOfSubMailField = value;
                    this.RaisePropertyChanged("NumOfSubMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubPhone {
            get {
                return this.NumOfSubPhoneField;
            }
            set {
                if ((this.NumOfSubPhoneField.Equals(value) != true)) {
                    this.NumOfSubPhoneField = value;
                    this.RaisePropertyChanged("NumOfSubPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubType {
            get {
                return this.NumOfSubTypeField;
            }
            set {
                if ((this.NumOfSubTypeField.Equals(value) != true)) {
                    this.NumOfSubTypeField = value;
                    this.RaisePropertyChanged("NumOfSubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubTypeComplete {
            get {
                return this.NumOfSubTypeCompleteField;
            }
            set {
                if ((this.NumOfSubTypeCompleteField.Equals(value) != true)) {
                    this.NumOfSubTypeCompleteField = value;
                    this.RaisePropertyChanged("NumOfSubTypeComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfSubTypeError {
            get {
                return this.NumOfSubTypeErrorField;
            }
            set {
                if ((this.NumOfSubTypeErrorField.Equals(value) != true)) {
                    this.NumOfSubTypeErrorField = value;
                    this.RaisePropertyChanged("NumOfSubTypeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfTitle {
            get {
                return this.NumOfTitleField;
            }
            set {
                if ((this.NumOfTitleField.Equals(value) != true)) {
                    this.NumOfTitleField = value;
                    this.RaisePropertyChanged("NumOfTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfTitleComplete {
            get {
                return this.NumOfTitleCompleteField;
            }
            set {
                if ((this.NumOfTitleCompleteField.Equals(value) != true)) {
                    this.NumOfTitleCompleteField = value;
                    this.RaisePropertyChanged("NumOfTitleComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfTitleError {
            get {
                return this.NumOfTitleErrorField;
            }
            set {
                if ((this.NumOfTitleErrorField.Equals(value) != true)) {
                    this.NumOfTitleErrorField = value;
                    this.RaisePropertyChanged("NumOfTitleError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numOfErrAddress {
            get {
                return this.numOfErrAddressField;
            }
            set {
                if ((this.numOfErrAddressField.Equals(value) != true)) {
                    this.numOfErrAddressField = value;
                    this.RaisePropertyChanged("numOfErrAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportHpTaskResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.SchedTask")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.StatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse))]
    public partial class ImportHpTaskResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ElapsedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] FileListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SchedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ElapsedTime {
            get {
                return this.ElapsedTimeField;
            }
            set {
                if ((this.ElapsedTimeField.Equals(value) != true)) {
                    this.ElapsedTimeField = value;
                    this.RaisePropertyChanged("ElapsedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] FileList {
            get {
                return this.FileListField;
            }
            set {
                if ((object.ReferenceEquals(this.FileListField, value) != true)) {
                    this.FileListField = value;
                    this.RaisePropertyChanged("FileList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfComplete {
            get {
                return this.NumOfCompleteField;
            }
            set {
                if ((this.NumOfCompleteField.Equals(value) != true)) {
                    this.NumOfCompleteField = value;
                    this.RaisePropertyChanged("NumOfComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfError {
            get {
                return this.NumOfErrorField;
            }
            set {
                if ((this.NumOfErrorField.Equals(value) != true)) {
                    this.NumOfErrorField = value;
                    this.RaisePropertyChanged("NumOfError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfTotal {
            get {
                return this.NumOfTotalField;
            }
            set {
                if ((this.NumOfTotalField.Equals(value) != true)) {
                    this.NumOfTotalField = value;
                    this.RaisePropertyChanged("NumOfTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SchedDateTime {
            get {
                return this.SchedDateTimeField;
            }
            set {
                if ((this.SchedDateTimeField.Equals(value) != true)) {
                    this.SchedDateTimeField = value;
                    this.RaisePropertyChanged("SchedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.ScheduledTask.CSMFileService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kiatnakinbank.com/services/CSM/CSMFileService", ConfigurationName="CSMFileService.ICSMFileService")]
    public interface ICSMFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FSResponse")]
        CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse GetFileAFS(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileA" +
            "FSResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse> GetFileAFSAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFSResponse")]
        CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse ExportFileAFS(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leAFSResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse> ExportFileAFSAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCB", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCBResponse")]
        CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse ExportFileNCB(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCB", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/ExportFi" +
            "leNCBResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse> ExportFileNCBAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DW", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DWResponse")]
        CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse GetFileBDW(string username, string password, bool skipSftp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DW", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileB" +
            "DWResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse> GetFileBDWAsync(string username, string password, bool skipSftp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "IS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "ISResponse")]
        CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse GetFileCIS(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "IS", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileC" +
            "ISResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse> GetFileCISAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "P", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "PResponse")]
        CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse GetFileHP(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "P", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMFileService/ICSMFileService/GetFileH" +
            "PResponse")]
        System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse> GetFileHPAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSMFileServiceChannel : CSM.ScheduledTask.CSMFileService.ICSMFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSMFileServiceClient : System.ServiceModel.ClientBase<CSM.ScheduledTask.CSMFileService.ICSMFileService>, CSM.ScheduledTask.CSMFileService.ICSMFileService {
        
        public CSMFileServiceClient() {
        }
        
        public CSMFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSMFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse GetFileAFS(string username, string password) {
            return base.Channel.GetFileAFS(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportAFSTaskResponse> GetFileAFSAsync(string username, string password) {
            return base.Channel.GetFileAFSAsync(username, password);
        }
        
        public CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse ExportFileAFS(string username, string password) {
            return base.Channel.ExportFileAFS(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ExportAFSTaskResponse> ExportFileAFSAsync(string username, string password) {
            return base.Channel.ExportFileAFSAsync(username, password);
        }
        
        public CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse ExportFileNCB(string username, string password) {
            return base.Channel.ExportFileNCB(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ExportNCBTaskResponse> ExportFileNCBAsync(string username, string password) {
            return base.Channel.ExportFileNCBAsync(username, password);
        }
        
        public CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse GetFileBDW(string username, string password, bool skipSftp) {
            return base.Channel.GetFileBDW(username, password, skipSftp);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportBDWTaskResponse> GetFileBDWAsync(string username, string password, bool skipSftp) {
            return base.Channel.GetFileBDWAsync(username, password, skipSftp);
        }
        
        public CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse GetFileCIS(string username, string password) {
            return base.Channel.GetFileCIS(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportCISTaskResponse> GetFileCISAsync(string username, string password) {
            return base.Channel.GetFileCISAsync(username, password);
        }
        
        public CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse GetFileHP(string username, string password) {
            return base.Channel.GetFileHP(username, password);
        }
        
        public System.Threading.Tasks.Task<CSM.ScheduledTask.CSMFileService.ImportHpTaskResponse> GetFileHPAsync(string username, string password) {
            return base.Channel.GetFileHPAsync(username, password);
        }
    }
}
