//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Web.DoNotCallBatchSelectService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/BatchSelectService.Message")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CSM.Web.DoNotCallBatchSelectService.DoNotCallBatchSelectServiceResponse))]
    public partial class BaseStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoNotCallBatchSelectServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/BatchSelectService.Message")]
    [System.SerializableAttribute()]
    public partial class DoNotCallBatchSelectServiceResponse : CSM.Web.DoNotCallBatchSelectService.BaseStatusResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.Web.DoNotCallBatchSelectService.ResponseStatus SLMStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSM.Web.DoNotCallBatchSelectService.SMGResponseStatus SMGStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.Web.DoNotCallBatchSelectService.ResponseStatus SLMStatus {
            get {
                return this.SLMStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SLMStatusField, value) != true)) {
                    this.SLMStatusField = value;
                    this.RaisePropertyChanged("SLMStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSM.Web.DoNotCallBatchSelectService.SMGResponseStatus SMGStatus {
            get {
                return this.SMGStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SMGStatusField, value) != true)) {
                    this.SMGStatusField = value;
                    this.RaisePropertyChanged("SMGStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/MTM.MasterService.Shared")]
    [System.SerializableAttribute()]
    public partial class ResponseStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResponseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseDate {
            get {
                return this.ResponseDateField;
            }
            set {
                if ((this.ResponseDateField.Equals(value) != true)) {
                    this.ResponseDateField = value;
                    this.RaisePropertyChanged("ResponseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMGResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/BatchSelectService.Message.SMG")]
    [System.SerializableAttribute()]
    public partial class SMGResponseStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.responseCodeField, value) != true)) {
                    this.responseCodeField = value;
                    this.RaisePropertyChanged("responseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMsg {
            get {
                return this.responseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMsgField, value) != true)) {
                    this.responseMsgField = value;
                    this.RaisePropertyChanged("responseMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="DoNotCallBatchSelectService.IDoNotCallBatchSelectService")]
    public interface IDoNotCallBatchSelectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDoNotCallBatchSelectService/ExecuteBatchSelectService", ReplyAction="urn:IDoNotCallBatchSelectService/ExecuteBatchSelectServiceResponse")]
        CSM.Web.DoNotCallBatchSelectService.DoNotCallBatchSelectServiceResponse ExecuteBatchSelectService();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDoNotCallBatchSelectService/ExecuteBatchSelectService", ReplyAction="urn:IDoNotCallBatchSelectService/ExecuteBatchSelectServiceResponse")]
        System.Threading.Tasks.Task<CSM.Web.DoNotCallBatchSelectService.DoNotCallBatchSelectServiceResponse> ExecuteBatchSelectServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoNotCallBatchSelectServiceChannel : CSM.Web.DoNotCallBatchSelectService.IDoNotCallBatchSelectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoNotCallBatchSelectServiceClient : System.ServiceModel.ClientBase<CSM.Web.DoNotCallBatchSelectService.IDoNotCallBatchSelectService>, CSM.Web.DoNotCallBatchSelectService.IDoNotCallBatchSelectService {
        
        public DoNotCallBatchSelectServiceClient() {
        }
        
        public DoNotCallBatchSelectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoNotCallBatchSelectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoNotCallBatchSelectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoNotCallBatchSelectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CSM.Web.DoNotCallBatchSelectService.DoNotCallBatchSelectServiceResponse ExecuteBatchSelectService() {
            return base.Channel.ExecuteBatchSelectService();
        }
        
        public System.Threading.Tasks.Task<CSM.Web.DoNotCallBatchSelectService.DoNotCallBatchSelectServiceResponse> ExecuteBatchSelectServiceAsync() {
            return base.Channel.ExecuteBatchSelectServiceAsync();
        }
    }
}
