//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Service.CBSHPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CBSHPService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://www.siebel.com/xml/KKB%20Res%20Activity%20GAble%20IO) does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SR_Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSM.Service.CBSHPService.SR_RequestResponse SR_Request(CSM.Service.CBSHPService.SR_RequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SR_Request", ReplyAction="*")]
        System.Threading.Tasks.Task<CSM.Service.CBSHPService.SR_RequestResponse> SR_RequestAsync(CSM.Service.CBSHPService.SR_RequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SR_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SR_Insert(CSM.Service.CBSHPService.KKB_EAI_ServiceRequest k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SR_Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SR_InsertAsync(CSM.Service.CBSHPService.KKB_EAI_ServiceRequest k);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/KKB%20Req%20Activity%20GAble%20IO")]
    public partial class SiebelMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Contact[] listOfKkbReqActivityGableIoField;
        
        private string messageId2Field;
        
        private string messageType2Field;
        
        private string intObjectName2Field;
        
        private string intObjectFormat2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Contact[] ListOfKkbReqActivityGableIo {
            get {
                return this.listOfKkbReqActivityGableIoField;
            }
            set {
                this.listOfKkbReqActivityGableIoField = value;
                this.RaisePropertyChanged("ListOfKkbReqActivityGableIo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageId2 {
            get {
                return this.messageId2Field;
            }
            set {
                this.messageId2Field = value;
                this.RaisePropertyChanged("MessageId2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageType2 {
            get {
                return this.messageType2Field;
            }
            set {
                this.messageType2Field = value;
                this.RaisePropertyChanged("MessageType2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntObjectName2 {
            get {
                return this.intObjectName2Field;
            }
            set {
                this.intObjectName2Field = value;
                this.RaisePropertyChanged("IntObjectName2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntObjectFormat2 {
            get {
                return this.intObjectFormat2Field;
            }
            set {
                this.intObjectFormat2Field = value;
                this.RaisePropertyChanged("IntObjectFormat2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/KKB%20Req%20Activity%20GAble%20IO")]
    public partial class Contact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string contactIdField;
        
        private string customerNumberField;
        
        private string sentDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
                this.RaisePropertyChanged("ContactId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SentDate {
            get {
                return this.sentDateField;
            }
            set {
                this.sentDateField = value;
                this.RaisePropertyChanged("SentDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/KKB%20Service%20Request%20IO")]
    public partial class KKB_EAI_ServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string integrationIdField;
        
        private string customerNumberField;
        
        private string financialAccountNumberField;
        
        private string sRTypeField;
        
        private string sRNumberField;
        
        private string areaField;
        
        private string subAreaField;
        
        private string abstractField;
        
        private string statusField;
        
        private string subStatusField;
        
        private string closedDateField;
        
        private string createdField;
        
        private string updatedField;
        
        private string contactFullNameField;
        
        private string createdByNameField;
        
        private string descriptionField;
        
        private string mainPhoneNumberField;
        
        private string ownedByIdField;
        
        private string ownerField;
        
        private string priorityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IntegrationId {
            get {
                return this.integrationIdField;
            }
            set {
                this.integrationIdField = value;
                this.RaisePropertyChanged("IntegrationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FinancialAccountNumber {
            get {
                return this.financialAccountNumberField;
            }
            set {
                this.financialAccountNumberField = value;
                this.RaisePropertyChanged("FinancialAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SRType {
            get {
                return this.sRTypeField;
            }
            set {
                this.sRTypeField = value;
                this.RaisePropertyChanged("SRType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SRNumber {
            get {
                return this.sRNumberField;
            }
            set {
                this.sRNumberField = value;
                this.RaisePropertyChanged("SRNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sub-Area", Order=7)]
        public string SubArea {
            get {
                return this.subAreaField;
            }
            set {
                this.subAreaField = value;
                this.RaisePropertyChanged("SubArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
                this.RaisePropertyChanged("Abstract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sub-Status", Order=10)]
        public string SubStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
                this.RaisePropertyChanged("SubStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ClosedDate {
            get {
                return this.closedDateField;
            }
            set {
                this.closedDateField = value;
                this.RaisePropertyChanged("ClosedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("Updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ContactFullName {
            get {
                return this.contactFullNameField;
            }
            set {
                this.contactFullNameField = value;
                this.RaisePropertyChanged("ContactFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CreatedByName {
            get {
                return this.createdByNameField;
            }
            set {
                this.createdByNameField = value;
                this.RaisePropertyChanged("CreatedByName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string MainPhoneNumber {
            get {
                return this.mainPhoneNumberField;
            }
            set {
                this.mainPhoneNumberField = value;
                this.RaisePropertyChanged("MainPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string OwnedById {
            get {
                return this.ownedByIdField;
            }
            set {
                this.ownedByIdField = value;
                this.RaisePropertyChanged("OwnedById");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/KKB%20Res%20Activity%20GAble%20IO")]
    public partial class KkbContactActivityVbc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactIdField;
        
        private string customerNumberField;
        
        private string descriptionField;
        
        private string financialAccountNumberField;
        
        private string openedField;
        
        private string ownerField;
        
        private string statusField;
        
        private string typeField;
        
        private string vehicleRegistNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
                this.RaisePropertyChanged("ContactId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FinancialAccountNumber {
            get {
                return this.financialAccountNumberField;
            }
            set {
                this.financialAccountNumberField = value;
                this.RaisePropertyChanged("FinancialAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Opened {
            get {
                return this.openedField;
            }
            set {
                this.openedField = value;
                this.RaisePropertyChanged("Opened");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string VehicleRegistNumber {
            get {
                return this.vehicleRegistNumberField;
            }
            set {
                this.vehicleRegistNumberField = value;
                this.RaisePropertyChanged("VehicleRegistNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SiebelMessage", Namespace="http://www.siebel.com/xml/KKB%20Res%20Activity%20GAble%20IO")]
    public partial class SiebelMessage1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KkbContactActivityVbc[] listOfKkbResActivityGableIoField;
        
        private string messageId3Field;
        
        private string messageType3Field;
        
        private string intObjectName3Field;
        
        private string intObjectFormat3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KkbContactActivityVbc[] ListOfKkbResActivityGableIo {
            get {
                return this.listOfKkbResActivityGableIoField;
            }
            set {
                this.listOfKkbResActivityGableIoField = value;
                this.RaisePropertyChanged("ListOfKkbResActivityGableIo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageId3 {
            get {
                return this.messageId3Field;
            }
            set {
                this.messageId3Field = value;
                this.RaisePropertyChanged("MessageId3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageType3 {
            get {
                return this.messageType3Field;
            }
            set {
                this.messageType3Field = value;
                this.RaisePropertyChanged("MessageType3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntObjectName3 {
            get {
                return this.intObjectName3Field;
            }
            set {
                this.intObjectName3Field = value;
                this.RaisePropertyChanged("IntObjectName3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntObjectFormat3 {
            get {
                return this.intObjectFormat3Field;
            }
            set {
                this.intObjectFormat3Field = value;
                this.RaisePropertyChanged("IntObjectFormat3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SR_Request", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SR_RequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.siebel.com/xml/KKB%20Req%20Activity%20GAble%20IO", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.siebel.com/xml/KKB%20Req%20Activity%20GAble%20IO")]
        public CSM.Service.CBSHPService.SiebelMessage c;
        
        public SR_RequestRequest() {
        }
        
        public SR_RequestRequest(CSM.Service.CBSHPService.SiebelMessage c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SR_RequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SR_RequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.siebel.com/xml/KKB%20Res%20Activity%20GAble%20IO", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.siebel.com/xml/KKB%20Res%20Activity%20GAble%20IO")]
        public CSM.Service.CBSHPService.SiebelMessage1 SR_RequestResult;
        
        public SR_RequestResponse() {
        }
        
        public SR_RequestResponse(CSM.Service.CBSHPService.SiebelMessage1 SR_RequestResult) {
            this.SR_RequestResult = SR_RequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CSM.Service.CBSHPService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CSM.Service.CBSHPService.ServiceSoap>, CSM.Service.CBSHPService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSM.Service.CBSHPService.SR_RequestResponse CSM.Service.CBSHPService.ServiceSoap.SR_Request(CSM.Service.CBSHPService.SR_RequestRequest request) {
            return base.Channel.SR_Request(request);
        }
        
        public CSM.Service.CBSHPService.SiebelMessage1 SR_Request(CSM.Service.CBSHPService.SiebelMessage c) {
            CSM.Service.CBSHPService.SR_RequestRequest inValue = new CSM.Service.CBSHPService.SR_RequestRequest();
            inValue.c = c;
            CSM.Service.CBSHPService.SR_RequestResponse retVal = ((CSM.Service.CBSHPService.ServiceSoap)(this)).SR_Request(inValue);
            return retVal.SR_RequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSM.Service.CBSHPService.SR_RequestResponse> CSM.Service.CBSHPService.ServiceSoap.SR_RequestAsync(CSM.Service.CBSHPService.SR_RequestRequest request) {
            return base.Channel.SR_RequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSM.Service.CBSHPService.SR_RequestResponse> SR_RequestAsync(CSM.Service.CBSHPService.SiebelMessage c) {
            CSM.Service.CBSHPService.SR_RequestRequest inValue = new CSM.Service.CBSHPService.SR_RequestRequest();
            inValue.c = c;
            return ((CSM.Service.CBSHPService.ServiceSoap)(this)).SR_RequestAsync(inValue);
        }
        
        public string SR_Insert(CSM.Service.CBSHPService.KKB_EAI_ServiceRequest k) {
            return base.Channel.SR_Insert(k);
        }
        
        public System.Threading.Tasks.Task<string> SR_InsertAsync(CSM.Service.CBSHPService.KKB_EAI_ServiceRequest k) {
            return base.Channel.SR_InsertAsync(k);
        }
    }
}
